### ISSUE TITLE
Add a way to include notes, if any exist

### ISSUE THREAD

**Issue by apollooakwood** [hadynz/obsidian-kindle-plugin#10]
Pretty self-explanatory I think, but as written now, it only snags highlights and leaves my notes behind. Would love to have notes, too. :)

**Comment by hadynz** [comment]
Thanks for raising. I hadn't implemented it on my first cut, even though it is quite a primary use case.

Implemented now in [release 0.0.8][1]. A new `{{highlight.note}}` variable has been introduced. You can add it to your existing template or delete the plugin's local `data.json` to start again.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.0.8
