### ISSUE TITLE
Nunjucks filters in Highlight template throws Template render error 

### ISSUE THREAD

**Issue by abishekmuthian** [hadynz/obsidian-kindle-plugin#101]
Thank you for creating this plugin, much appreciated.

I'm trying to use Nunjucks filter '[replace](https://mozilla.github.io/nunjucks/templating.html#replace)' in the Highlight template,
```

{{ text | replace('4', '.') }}

{% if note %}{{note}}{% endif %}

---
```
But it results in template render error,

```
Error parsing
.../My clippings.txt.

Template render error:(unknown path)
TypeError: Cannot read property 'lineno' of undefined
```
My actual goal is to use regex with the replace filter, But since it didn't work I tried a basic replace as sighted above.

**Comment by hadynz** [comment]
Thanks for raising this @abishekmuthian. I understand this issue and it is a valid bug. 

To support resync, the plugin adds a "block reference" (e.g. `^ref-1233`) at the end of a highlight (rendered using `{{ text }}` tags in nunjucks). The plugin has not catered for the fact that you could be using a nunjucks modifier such as `replace` to manipulate the content.

Will fix shortly.

**Comment by abishekmuthian** [comment]
Thanks for acknowledging the issue.

I read Hacker News on my Kindle using [hntokindle.com](https://hntokindle.com) [Full Disclosure: I built it] for note taking and accessibility reasons.

I had been waiting for obsidian-kindle-plugin type solution to assimilate the Kindle highlights & notes which I've created for those Hacker News comments on Kindle.

e.g. A typical Hacker News highlight of a comment with a custom note looks like this after being parsed by the plugin(removed appLink and location via template,

```
## Highlights
Havoc 18 hours ago | next [–] Somewhat surprised none of the major clouds off true sandboxed learning environments as a competitive advantage. i.e. We will not charge you more than $100 no matter what. Sure that doesn't work for enterprise stuff that has to be online, but there is a big market for people that can swallow $100 accidents but not 15k. And whoever offers that first will attract the cautious crowd. I've got friends that point blank refuse to use cloud due to the open ended billing. (Azure comes closes as best as I can tell...their MSDN style credits seem to be true hard capped) [Invariably this get's the "but what to do about the data...can't just delete it...yes you can. The $100 crowd is ok with that. 30 day grace then delete it...much like anyone with an unpaid bill]  ^ref-8930

need-gap

---
```
So my immediate goal is to replace `18 hours ago | next [–]`  with `:` using a combination of Nunjucks replace with regEx. I mistakenly assumed {{ text }} is the actual highlight text content and so I tried,

`{{ text | replace( r/([0-9]{1,2}) (hours|minutes) (ago) (\| ((next \[\–\])|((parent|prev) \| next \[\–\]))|\[\–\])+/gmi , ":" ) }}`

Now I've learnt from you that {{ text }} is not the highlight text itself but the `^ref-8930` and that Nujucks filters require additional implementation.

So to confirm we're looking at these implementations for the plugin,
1. Making the highlight text available to the template.
2. Making complete templating features of Nunjucks available to the user.
3. Making `bookTemplate.njk` user editable as well via settings. (An auxiliary implementation which can add further value as downloaded content don't have typical metadata of a book.)

I'm not very familiar with the technologies used with the project(TS, svelte, Nunjucks) and so I'll have to undergo a learning curve to make some useful code level contributions.

I came across https://github.com/hadynz/obsidian-kindle-plugin/blob/432dac28326b2a9b208c01c97129d928babdbada/src/renderer/index.ts#L25 where you're using `addExtension` to add support for Trim, BlockRef, Does that mean we have to add corresponding extensions for replace, regEx etc. specifically?

P.S. All these might sound like a very specific use case but lot of people use their Kindle to read downloaded content via services like instapaper (or) 'Send to Kindle' type extensions on their browser for which obsidian-kindle-plugin would be a natural fit to extend the usefulness of Kindle highlights and note taking.

**Comment by hadynz** [comment]
> Now I've learnt from you that {{ text }} is not the highlight text itself but the ^ref-8930 and that Nujucks filters require additional implementation.

No. That's not quite right.

`{{ text }}` is indeed the reference to the annotation text. So your original attempt was right.

What the plugin also tries to do, is to dynamically find which **line** contains `{{ text }}` to dynamically add a custom block reference at the end of the line that it later uses for resyncing. The way that the plugin was looking for this nunjucks variable was quite brittle and did not take into account that users could be using nunjucks filters and other extensions.

This should be fixed in [1.1.2][1]. Give it a go and let me know if it works for you too.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.1.2

**Comment by abishekmuthian** [comment]
I stand corrected regarding `{{ text }}`, thanks.

Tried 1.1.2 and these are my results,

Simple replace works,

`{{ text | replace("foo","bar") }}`

Anything with regEx is not accepted as a valid template as [nunjucks regex is without quotes](https://github.com/mozilla/nunjucks/issues/366),

e.g.

`{{ text | replace (r/foo/, "bar") }}`

(or)

```
{% set regExp = r/foo/ %}

{{ text | replace(regExp, "bar")
```
Both are rejected as valid template.

Enclosing the regEx in quotes is accepted as a template but doesn't function as I suspect regEx in Nunucks shouldn't be in quotes.

I think template validation or sanitization in the plugin is now expecting or creating pure strings.

**Comment by hadynz** [comment]
So that we can confirm if the original issue that you had raised was resolved by the last release, you can bypass the validation that the plugin uses and modify the plugin's `data.json` file directly. Simply set `highlightTemplate` to the nunjucks template that you want and it should be picked up by the plugin.

I'll look into fixing the false negative issue of validation after I am done with another task.

**Comment by abishekmuthian** [comment]
The original issue was that the Nunjucks templating feature set wasn't available for custom `highlightTemplate`, With the release of [1.1.2](https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.1.2) this issue seems to have been resolved in my limited testing of Nunjucks filter like [replace](https://mozilla.github.io/nunjucks/templating.html#replace) with regEx.

> you can bypass the validation that the plugin uses and modify the plugin's data.json file directly. Simply set highlightTemplate to the nunjucks template that you want and it should be picked up by the plugin.

This works, provided Obsidian is restarted after making changes to `data.json` else it would replace the custom template with what's available by default or empty string.

The current issue is that template validation on the UI(settings) is not compatible with Nunjucks feature set. (Which can be addressed as per your priority).

P.S. As of 1.1.2 **reset sync**  isn't available and I'm deleting the *.md files manually each time to resync for testing, Is this the recommended way to do now? Also I don't prefer deleting data.json anymore as it now contains custom template.

**Comment by hadynz** [comment]
I've just tried to use a regex example from Nunjuck's [documentation][1] and the plugin's validation worked as expected:

```
{% set regExp = r/^foo.*/g %}
{% if regExp.test('foo') %}
  Foo in the house!
{% endif %}
```

Is it possible that your regex is malformed? The best way to test this is to create an independent project with Nunjucks and test your template syntax (with your regex) in isolation.

[1]: https://mozilla.github.io/nunjucks/templating.html#regular-expressions

**Comment by hadynz** [comment]
> P.S. As of 1.1.2 reset sync isn't available and I'm deleting the *.md files manually each time to resync for testing, Is this the recommended way to do now? Also I don't prefer deleting data.json anymore as it now contains custom template.

I removed the reset function in the plugin as I didn't feel it was particularly useful. It wasn't resetting any of your files, but was simply resetting "state" information (such as when you last synced, number of books/annotations synced, etc).

With the implementation of resync, the calculation of number of books and annotations is always accurately fetched by parsing all your `.md` files in your vault and looking at frontmatter. So the only state that the plugin keeps track of are your settings. I could look at adding an option of "reset settings to defaults", but then again no one has really asked for it.

To answer your question - deleting `*.md` files and resyncing is perfectly fine and the plugin works well with that.

**Comment by abishekmuthian** [comment]
> Is it possible that your regex is malformed? The best way to test this is to create an independent project with Nunjucks and test your template syntax (with your regex) in isolation.

The issue is with how the regEx in the  `replace` filter is being validated in the plugin, The code below is not accepted as valid template but works in `data.json` :

```
{{ text | replace(r/([0-9]{1,2}) (hour|hours|minutes) (ago) (\| ((next \[\–\])|(((root \| parent)|(parent \| prev)|parent|prev) |\| next \[\–\]))|\[\–\])+/gmi, ":") }} — location: [{{location}}]({{appLink}})

{% if note %}{{note}}{% endif %}

---
```
If the regEx is enclosed in `" "` inside `replace` then it would be accepted as a valid template, but it's not valid Nunjucks syntax for regEx in replace filter.

I've given more examples and linked to actual discussion on **regEx with replace filter** on Nunjucks project in my previous comment - https://github.com/hadynz/obsidian-kindle-plugin/issues/101#issuecomment-968064896

**Comment by hadynz** [comment]
Figured what the issue was after recreating it. Have fixed it in [1.3.1][1]. Try it out and let me know if this has solved the problem you were running into, and finally completed your workflow.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.3.1

**Comment by abishekmuthian** [comment]
The template with replace filter containing regEx is now being accepted  as a valid template on 1.3.1!

But unfortunately something else has broken with the sync, **It now syncs only ~ 16% of books from the My Clippings.txt** 

Here are the troubleshooting steps I've taken so far in vain,

1. Deleted  *.md files, data.json and synced again.
2. Removed the custom template and synced again.
3. Deleted the plugin, Installed fresh and synced again.
4. Disabled 'Download book metadata' and synced again.

It synced only same books each time i.e. ~ 16% of total books.

I reverted back to 1.1.2 to confirm that there was no issue with the My Clippings.txt file as it syncs all the books (or at least same number of books since I started testing the plugin).

I'm attaching the `My Clippings.txt`
[My Clippings.txt](https://github.com/hadynz/obsidian-kindle-plugin/files/7539172/My.Clippings.txt)

If you can point me to documentation on how to collect the relevant logs from standalone Obsidian Linux application I can attach them too.

**Comment by hadynz** [comment]
I've recently had to rewrite how the plugin parses the My Clippings file. It was missing notes and sometimes attaching them to the wrong annotation. 

This should be straight forward to fix since you've sent me your file. It is possible that there is a use case in your file that has not been catered for.

**Comment by abishekmuthian** [comment]
Also comparing with v1.1.2 should make the difference clear even though I'm not entirely sure whether all the books were synced by it in the first place since you mention pre-existing issues; But definitely 264 books synced is better than 40.

**Comment by hadynz** [comment]
@abishekmuthian I really, really hope that with the latest version [1.4.0][1] we have finally resolved all the issues that you've been encountering 😆. Let me know if we have finally nailed it. Cheers!

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.0

**Comment by abishekmuthian** [comment]
447 Books, 486 Highlights and  my template works with [1.4.1](https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.1)🤟  Well done!

I checked the highlights at random and everything seems to be in order.

I will close this issue tomorrow after syncing few more fresh highlights.

Should we start a discussion about merits of bringing in custom `bookTemplate`? Because there are lot of instapaper  users with similar use case as mine who'd like to edit the metadata for highlights from the downloaded content.

**Comment by jesuserro** [comment]
> Thanks for raising this @abishekmuthian. I understand this issue and it is a valid bug.
> 
> To support resync, the plugin adds a "block reference" (e.g. `^ref-1233`) at the end of a highlight (rendered using `{{ text }}` tags in nunjucks). The plugin has not catered for the fact that you could be using a nunjucks modifier such as `replace` to manipulate the content.
> 
> Will fix shortly.

Hi, Hadynz: is there a way to ignore this "block reference" at the end of highlights? I'm forking your your project for my own purposes. All my paragraphs end with an annoying block reference like "^ref-1233". I cannot get rid of it. I'm using Obsidian. Greetings!
