### ISSUE TITLE
Metadata's Reference is an internal link

### ISSUE THREAD

**Issue by jelomu** [hadynz/obsidian-kindle-plugin#109]
Dear developer of this wonderful plugin,

I have noticed the Reference field in the metadata section, the one that contains a link to the book on Amazon, is formatted as an internal link and not an external link. (v 1.3.1)

It is not ideal as it creates empty notes on the graph that don't really cover any use case that I can think of.
I assume it is not on purpose and can be fixed in an upcoming version.
If I am missing something please let me know.

Cheers

**Comment by hadynz** [comment]
That's a good call out. I'll make a fix for it shortly.

**Comment by jelomu** [comment]
Thanks hadynz!

**Comment by hadynz** [comment]
This has been fixed in [1.4.0][1]. Please give it a try and let me know if it has resolved this issue for you.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.0

**Comment by jelomu** [comment]
Perfect, thank you @hadynz !
