### ISSUE TITLE
Extra line is added when template is inserted

### ISSUE THREAD

**Issue by retospect** [hadynz/obsidian-kindle-plugin#115]
My template is 
"- {{ text }} - [{{ location }}]({{ appLink }}) {% if note %}{{ note }} {% endif %}" 
(without a trailing new line)

and the goal is that it comes out as

- quote linkid
- quote linkid2
- quote...

It does come out with extra spaces though:

- quote linkid

- quote linkid

- quote linkid

The extra space causes the quotes to be double-spaced instead of condensed.

**Comment by vii33** [comment]
Just tested this, works on my machine. @retospect: Did you check if you have any trailing linebreaks / whitespaces?

**Template:**
```
- {{ text }} -- [{{ location }}]({{ appLink }}) {% if note %}{{ note }} {% endif %}
```
**Result:**
```
## Highlights
- YoloR has many features... -- [43]()  ^ref-11627
- YOLOR, you can enroll in our YOLOR course here. -- [54]()  ^ref-17234
```
![grafik](https://user-images.githubusercontent.com/1887246/165582734-1af082e3-b5f5-411b-b035-329dcbc65f67.png)

I think this issue can be closed.
