### ISSUE TITLE
Option to sync with Kindle Apps (email)

### ISSUE THREAD

**Issue by zzdcgg** [hadynz/obsidian-kindle-plugin#12]
@hadynz Hey - I have a Kindle account from China and cannot sync with this plugin. Had the same issue whey trying to sync with ReadWise. ReadWise pointed me to 2 alternative solutions: 1. Kindle Device (My Clippings); 2. Kindle Apps (Email). More details can be found through the line below:

https://help.readwise.io/article/30-how-do-i-import-highlights-from-personal-documents-on-kindle

I understand that you are working on the 1st solution (My Clippings) which is great. I wonder whether the 2nd option, Kindle Apps (Email), is also feasible. To me, the 2nd option is much more convenient.

Thanks a million!

**Comment by hadynz** [comment]
The solution to use `My Clippings` has now been made available (starting from release [0.1.0][1]).

As for the option of supporting "email"... this is made possible by an externally hosted service like Readme. They have most probably created an implementation to scan any attachments coming from `add@readwise.io`, identifying your identity and Readwise from the email's `from address`, and then uploaded highlights from the attachment to their service.

This feature cannot be implemented via an Obsidian plugin. I would have to create a comparable service like Readwise. 

This currently falls out of scope for this plugin. 

Let me know if you would be happy to close this issue.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.1.0

**Comment by zzdcgg** [comment]
Got it. Thanks!
