### ISSUE TITLE
Template no longer working after update. 

### ISSUE THREAD

**Issue by FrocketGaming** [hadynz/obsidian-kindle-plugin#124]
![2021-11-25 10_45_28-Vault - Obsidian v0 12 19](https://user-images.githubusercontent.com/74742645/143470609-1ef433ab-9598-4b69-8bdf-6b077a48d228.png)
I noticed that the data.json file has my old template as the "noteTemplate" but most of the items in this template are not showing up. Photo attached so you can see what it does vs what I'm expecting from the template below. 

"---\ntitle: {{title}}\nauthor: {% if author %}{{author}}{% endif %}\nyear:\ntags:\npages: {{pages}}\nread:\nrating:\n---\n# {{title}}\n\n### `ris:FileInfo` References\nRelevant Notes:\nRelevant Books:\n\n### Summary\n\n### `ris:Information` Key Ideas\n\n### `ris:ChatQuote` Key Quotes\n\n### `ris:Book3` Book Highlights\n{% for highlight in highlights %}Pg. {{highlight.page}}\n- {{highlight.text}}\n{%- if highlight.note %}{{highlight.note}}{% endif %} \n{% endfor %}\n\n#### Footnotes"

Also, how do I get rid of the ^ref at the end of each note?

**Comment by hadynz** [comment]
You cannot get rid of the `^ref-` block quote at the end of a line with an annotation. The plugin requires this reference to understand what annotations are in the file, in order to be able to resync future new highlights.

**Comment by FrocketGaming** [comment]
What about the template issue, how do I resolve that?

**Comment by hadynz** [comment]
> I would like an option to prevent the reference block. When I import a book, I am finished with it and it will no longer require another sync.

As I explained above, the referenced block is now required in order for the plugin to support resync in case any new annotations were added later on for a given book. Adding an option to remove the reference block will add unnecessary complexity to the plugin (both technically and from a usability perspective). I am not currently inclined to add this unless it is a popular request  by many users.

> What about the template issue, how do I resolve that?

I am not sure if I understood the template issue that you are referring to. Do you mind describing it again. Can you also confirm what version of the plugin are you currently running please.

**Comment by FrocketGaming** [comment]
@hadynz I understand that it's required, simply saying it isn't something I prefer to have if it were possible. For now I'll use Find & Replace to edit them all out at one time.

Regarding my issue with the template... The first pst at the top shows what my old note template was for this plugin

`"---\ntitle: {{title}}\nauthor: {% if author %}{{author}}{% endif %}\nyear:\ntags:\npages: {{pages}}\nread:\nrating:\n---\n# {{title}}\n\n### ris:FileInfo References\nRelevant Notes:\nRelevant Books:\n\n### Summary\n\n### ris:Information Key Ideas\n\n### ris:ChatQuote Key Quotes\n\n### ris:Book3 Book Highlights\n{% for highlight in highlights %}Pg. {{highlight.page}}\n- {{highlight.text}}\n{%- if highlight.note %}{{highlight.note}}{% endif %} \n{% endfor %}\n\n#### Footnotes"`

It's the structure I use for all the books I import. Since recently updating this plugin (1.5.2) it removed my note template as the plugin was restructured in some ways.

I found my note template in the data.json file which suggests to me it is still being used as the template when I import books but the image in my original posts shows that much of what's in my note template itself is not showing up. 

For example, all of this is in the data.json but isn't on the page when I import...
`n### ris:FileInfo References\nRelevant Notes:\nRelevant Books:\n\n### Summary\n\n### ris:Information Key Ideas\n\n### ris:ChatQuote Key Quotes\n\n### ris:Book3 Book Highlights\n{% for highlight in highlights %}`

**How do I get it to work with my original template?** Otherwise I'll have to restructure every single book I import which is a huge waste of time. I'd rather just go back to the previous version of this plugin without having to work on removing the location data and ^ref blocks.

**Comment by hadynz** [comment]
> @hadynz I understand that it's required, simply saying it isn't something I prefer to have if it were possible. For now I'll use Find & Replace to edit them all out at one time.

You need to be careful when you do this. If you were to add any new annotation for a book that you synced before, the plugin will detect that there is a new annotation and will trigger a resync. Because you are planning to remove all block references generated by the plugin, the plugin will make an assumption that no annotations have been synced before. The resync will then bring over all your annotations, leading to duplication.

> It's the structure I use for all the books I import. Since recently updating this plugin (1.5.2) it removed my note template as the plugin was restructured in some ways.

Before 1.5.2, the plugin had two customisable templates:

1. Annotation template — how an individual highlight is rendered
2. Book template — how your entire highlight is written in the file

I removed the second template to reduce complexity in the plugin. Am I correct in my understand that this is the template that you want to bring back again?

**Comment by FrocketGaming** [comment]
Yeah, the book template is what I used to lay out the entire way the book was put into Obsidian so it matched up with how I write up my other notes. With how it is now I have to spend 5-10 minutes for each book to structure and format it how I do all my other notes.

**Comment by FrocketGaming** [comment]
Is there a way to roll back the plugin to a previous version where the previously mentioned feature still worked?

**Comment by Warden20** [comment]
The book template saves time formatting the metadata. Can you add it again?

**Comment by hadynz** [comment]
I can bring back the feature to format the overall book template. If people can share what some of their templates look like, it would be quite useful when looking at making this feature again.

In terms of the `^ref` at each note, there is no plans to remove it or make it optional at this stage.

**Comment by FrocketGaming** [comment]
> I can bring back the feature to format the overall book template. If people can share what some of their templates look like, it would be quite useful when looking at making this feature again.
> 
> In terms of the `^ref` at each note, there is no plans to remove it or make it optional at this stage.

Here is the data I had in the original template before it was removed. 

`"---\ntitle: {{title}}\nauthor: {% if author %}{{author}}{% endif %}\nyear:\ntags:\npages: {{pages}}\nread:\nrating:\n---\n# {{title}}\n\n### ris:FileInfo References\nRelevant Notes:\nRelevant Books:\n\n### Summary\n\n### ris:Information Key Ideas\n\n### ris:ChatQuote Key Quotes\n\n### ris:Book3 Book Highlights\n{% for highlight in highlights %}Pg. {{highlight.page}}\n- {{highlight.text}}\n{%- if highlight.note %}{{highlight.note}}{% endif %} \n{% endfor %}\n\n#### Footnotes"

It ended up looking something like this in edit mode.

![image](https://user-images.githubusercontent.com/74742645/152621431-e37c2afb-707a-47e6-9dcc-8ca5a225ad50.png)

**Comment by FrocketGaming** [comment]
Is this something still being considered for a future update?

**Comment by hadynz** [comment]
Hey @FrocketGaming. I am going through all issues and just noticed this issue is yet to be resolved.

After re-reading this thread again, I think I understand the issue that you are encountering. Let me know if I understood it correctly and if my explanation/solution works for you.

When you manually open up `data.json`, you see the original template that you had still correctly stored against a field called `noteTemplate` and you are wondering why it is not longer being used?

`noteTemplate` is now a deprecated field. There isn't a replacement for it. You can control how an individual highlight is formatted by modifying `highlightTemplate`.

With that said, I will be introducing something soon to give you more control to format (a) front matter data, (b) overall template.

**Comment by hadynz** [comment]
@FrocketGaming thanks for your patience. I've implemented what you've been asking for in release 1.6.0. You now have the ability of customising the layout of your main template as you've asked for.

If you can test it out that would be great.

**Comment by FrocketGaming** [comment]
@hadynz whoa. Completely forgot about this. Thanks for your efforts I'll check this out.
