### ISSUE TITLE
Highlights from books written in Japanese looking incomplete on Obsidian

### ISSUE THREAD

**Issue by hwatanabe-tufs** [hadynz/obsidian-kindle-plugin#125]
First, thank you for your great work. This plugin has really allowed me to work more productively with Obsidian.

Getting into the issue, I noticed that those Kindle highlights from books written in Japanese did not appear to reflect their entire parts whereas those from English books worked properly. Below are the example. The first one represents my Obsidian while the second one my Kindle with both showing the same highlight.

![173344](https://user-images.githubusercontent.com/86272619/145501585-a78675d8-84b7-4f2e-ba62-75263fe44767.png)
![101524](https://user-images.githubusercontent.com/86272619/145501595-9f692a06-7617-473b-b7b1-0759c23348d7.png)

This is just a slight difference though, the last two or three letters are missing as you can see, and the same problem happens even though the extent of missing words differs slightly every time.

Just so you know, I've set Amazon region to Japan(amazon.co.jp) and always sync manually.
・Kindle Highlights: Version 1.5.2
・Obsidian: v0.12.19

Let me know if you need more details.
I'd be happy if you could help me solve the issue.

**Comment by hadynz** [comment]
How do your highlights compare between your Kindle and what Amazon captures in their online editors — https://read.amazon.co.jp/notebook? Are your highlights there missing any characters, or are they being rendered in completeness?

**Comment by hwatanabe-tufs** [comment]
The online editor looks differently compared to my Kindle but the same as what I get on my Obsidian, missing the same characters too.

![120246](https://user-images.githubusercontent.com/86272619/145510825-9e3a3f88-c337-4370-8ee4-5327f1b83f44.png)

With this considered, am I right in thinking that your plugin works properly and the issue is in the online editor?

**Comment by hadynz** [comment]
That's correct. 

The "source of truth" for all highlights is Amazon's cloud. The plugin simply automates the process of downloading it to your local machine and into Obsidian. So this issue would fall outside the scope of the plugin.

One other option that you could try is to connect your Kindle to your local machine, and sync your highlights from the My Clippings.txt file on the device. It is possible that will have all your annotations intact.

**Comment by hwatanabe-tufs** [comment]
I should have checked beforehand where the problem occurred more carefully.
Sorry that I was totally missing the point and thank you so much for your help.

> One other option that you could try is to connect your Kindle to your local machine, and sync your highlights from the My Clippings.txt file on the device. It is possible that will have all your annotations intact.

That would be the best solution. I am going to give it a try.
Again, thank you very much.

**Comment by hwatanabe-tufs** [comment]
I've tried the option you suggested and all done successfully.
I am just letting you know. Thank you.
