### ISSUE TITLE
More customizable note name options

### ISSUE THREAD

**Issue by IloveJesusmyKing** [hadynz/obsidian-kindle-plugin#126]
I am interested in using this plugin but have a compatibility issue with the note names. For example, I put a date in my book note names like "2021-11-01 BOOK TITLE".

Is there any way this code can be changed to enable more flexible names?

**Comment by hadynz** [comment]
The plugin gives you two powerful forms of flexibility to be in control of your file naming convention.

**1. Flexible naming convention**
The plugin does not rely on the naming convention of any of the files that it produces. It only relies on the front matter information at the top of the file. This means that you can rename any file with the exact name that you would like after it is first created. The plugin will keep updating contents of the file going forward.

**2. Configure file name templates**
In the plugin's settings you can configure a custom [Nunjucks template][1] for the filename. There are currently only three variables that the plugin exposes (title, short title and author).

![image](https://user-images.githubusercontent.com/315585/145704526-caf08fa1-a0c9-49f9-85d1-ca0f79962191.png)

Can a combination of the above two solve your problem?

What "date" did you want to have in the file title? Published date? First read date? Curious to know more about your requirement and your use case for it. That will help me prioritise this work if its a new enhancement. 

[1]: https://mozilla.github.io/nunjucks/templating.html

**Comment by IloveJesusmyKing** [comment]
Thank you for clarifying this! Your recommendation is what I am looking for. I renamed the note as desired after it was created!
