### ISSUE TITLE
Parse and include highlight date

### ISSUE THREAD

**Issue by rachellim** [hadynz/obsidian-kindle-plugin#130]
**Is your feature request related to a problem? Please describe.**
my-clippings.txt includes highlight date. It would be amazing if this plugin could parse that and have that as a template variable for highlights.

**Comment by hadynz** [comment]
This gets tricky given that the date is not always in English. I am considering implementing this with a caveat that it only works for certain languages.

**Comment by hadynz** [comment]
Done. Added your feature request in [1.6.2][1].

If you can let me know if it works as expected in thread, that would be great.

![image](https://user-images.githubusercontent.com/315585/173212080-1238cc5a-66f0-4d79-ad4e-42781919f7b6.png)

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.6.2
