### ISSUE TITLE
Add more template tags

### ISSUE THREAD

**Issue by yfr** [hadynz/obsidian-kindle-plugin#135]
**Is your feature request related to a problem? Please describe.**
I would like to have a template tag to the `read.amazon.com` url like `https://read.amazon.com/?asin=B003ODIWEG&language=en-US`

**Describe the solution you'd like**
Add a new template tag. I.E `readLink` (like `appLink` for the kindle app) 

**Describe alternatives you've considered**
One could build these link with the book metadata, maybe?

**Comment by orbitaloop** [comment]
This url tag would be great!

Also a tag to know the date when we read (and finished) the book would be awesome (ex. taking the first or latest date of the highlight).

In the My Clippings.txt, there is the date for each highlight. Ex: "Added on Saturday, January 31, 2015 12:32:03 AM"

**Comment by duganj** [comment]
Another vote for being able to pull in the date each highlight was made, even better if it would be possible to specify the date format so that it would link to daily notes of the same date, etc.

**Comment by hadynz** [comment]
@yfr this already exists (for any book that is bought via Amazon, since it will have an associated ASIN)

**Comment by yfr** [comment]
Thanks. This works for me.
