### ISSUE TITLE
Add book/frontmatter templates to plugin config

### ISSUE THREAD

**Issue by yfr** [hadynz/obsidian-kindle-plugin#136]
**Is your feature request related to a problem? Please describe.**
I like to be able to edit the metadata of the book in the plugin settings.

**Describe the solution you'd like**
Add another input for the meta data templates.

**Additional context**
Maybe the frontmatter part of the book could also be made as a template.

**Comment by hadynz** [comment]
I've implemented your request in [version 1.6.0][1]. When you go to the plugin settings, you will be able to customise the default template used for note highlights. You should be able to add a YAML front matter section, or add double colons as you wanted to play well with Dataview.

If you can confirm this release works well for you that would be great.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.6.0

**Comment by yfr** [comment]
this works perfect! thanks!

**Comment by arielylim** [comment]
Trying this out now -- I can add/customize the template in the settings


<img width="520" alt="Strategic_Storytelling_-_PARA_-_Obsidian_v1_3_5" src="https://github.com/hadynz/obsidian-kindle-plugin/assets/60095540/e8827404-4068-4abf-bb45-132dc4cacd33">

But I can't seem to edit/change the actual front matter itself. 

<img width="782" alt="Strategic_Storytelling_-_PARA_-_Obsidian_v1_3_5" src="https://github.com/hadynz/obsidian-kindle-plugin/assets/60095540/c1768a4b-f073-4a9d-bb17-bc8e27742eca">

**Comment by matiasdiez** [comment]
Hi. I am interested to change the frontmatter, will be very usefull.
