### ISSUE TITLE
not syncing highlights of all annotated books

### ISSUE THREAD

**Issue by sinayanaik** [hadynz/obsidian-kindle-plugin#137]
I have over 100 books but only highlights of 10 books are being synced no matter how many times i hit sync

I want it to sync highlights from all my books

![image](https://user-images.githubusercontent.com/72493351/149624878-edf5d4c5-ffd8-4bb3-82cc-91d80cf97e21.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Plugin version 1.5.2
 - Obsidian version 0.13.19

**Comment by sinayanaik** [comment]
I tried The same in Windows and it is only syncing 10 books
![image](https://user-images.githubusercontent.com/72493351/149625350-cf2348fa-0655-4433-a8b6-b9275f30fcf4.png)

**Comment by hadynz** [comment]
@sinayanaik good place to start with such a bug is to confirm your statement:

> I have over 100 books but only highlights of 10 books are being synced no matter how many times i hit sync

Because you are syncing via the cloud, this plugin uses https://read.amazon.com/notebook as its source of truth. Can you login there and confirm that you can see all your 100 books? (a screenshot will help me).
