### ISSUE TITLE
Is there a limit to the number of books the plugin can import highlights from?

### ISSUE THREAD

**Issue by jlouw** [hadynz/obsidian-kindle-plugin#14]
Thanks for the plugin.

Is there a limit to the number of books the plugin can import highlights from?

When I import highlights into Obsidian via Amazon I can only import the first 25 or so books. If I open a book further down the list (>25) in the amazon book webreader, the book will then appear at the top-of-the-list of books in the highlights page.

Then the plugin will import the highlights from the book, but stop again at about 25 or so books.

What am I missing something, or could it be a bug?

**Comment by hadynz** [comment]
> Is there a limit to the number of books the plugin can import highlights from?
No, there isn't. This plugin is designed and can scale to be able to handle 100s of books if required.

The description that you describe sounds very much like a "pagination" problem. However, I am surprised that is the behaviour that you are encountering.

When getting your notes via Amazon, the plugin logs on your behalf to https://read.amazon.com/notebook and iterates through every listed book in your library, and fetches highlights just like you would do in a normal browser. 

The list of books in your library (see red box below) to my knowledge is **never paginated**. So I am surprised that you are getting the behaviour that you are seeing.

![image](https://user-images.githubusercontent.com/315585/116864974-dd051a80-ac5c-11eb-9820-f4e25f3bf83f.png)

Can you visit https://read.amazon.com/notebook and confirm the following:

1. Total number of books in your library - _it is possible that you have so many books above a certain threshold that pushes Amazon to paginates the list of books you can view_
2. Are you able to see all of your books listed in the left handside? Or are you only able to see the first 25 books before pagination kicks in?

**Comment by jlouw** [comment]
Hi Hady

Total nr of books with highlights: about 150
Yes, I can see all the books on the left when I scroll down, but it might
be auto loading...not sure
This is what I see in google chrome devtools.
It looks like there is some type of pagination happening after about 25
books....?

[image: image.png]

Thanks,
Jean

**Comment by hadynz** [comment]
Thanks for the screenshot Jean.

I can confirm that I am actually able to reproduce the problem myself. I have about 95 books in my library. I noticed that my plugin has been fetching the first 93 books, and completely missing the last two books.

Whilst it is not exactly the same behaviour that you are seeing - consistently pagination is taking place in 25 book chunks; there is a chance it is because of the same problem.

I'll work on a fix this week and let you know when it's done and you can test at your end.

**Comment by jlouw** [comment]
Great, thanks!

**Comment by hadynz** [comment]
@jlouw can you see if release [0.1.2][1] loads all the books in your library?

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.1.2

**Comment by jlouw** [comment]
Hi Hady

Yes, it does, thanks.

Will let you know if I notice anything....

**Comment by hadynz** [comment]
Are you happy that this issue has been resolved and can be closed?

**Comment by jlouw** [comment]
Yes, thanks!
