### ISSUE TITLE
Add disclaimer about export limits

### ISSUE THREAD

**Issue by jonesmartins** [hadynz/obsidian-kindle-plugin#148]
**Is your feature request related to a problem? Please describe.**

Amazon says long highlights will not be completely shown due to export limits. This "feature" affects the plugin, and there's nothing you can do about it. 

**Describe the solution you'd like**

Add a big disclaimer everywhere about this export limit until there's an alternative.

**Describe alternatives you've considered**

I don't have a Kindle device, but using "My clippings.txt" instead would be a "fix" to this limit issue (I think).

**Additional context**

None.

**Comment by TariqMK** [comment]
Nothing to add except that you're correct. Using sideloaded books (with DRM removed) and the MyClippings.txt file removes this limit.

**Comment by jonesmartins** [comment]
It's a lesson on how to highlight books effectively, instead of selecting whole sections in one go. :laughing:
