### ISSUE TITLE
[BUG] Cannot be enabled on iPad

### ISSUE THREAD

**Issue by robertandrews** [hadynz/obsidian-kindle-plugin#151]
**Describe the bug**
In Community Plugins, I click the enable toggle. It makes a momentary animation, but does not switch on.

**Comment by hadynz** [comment]
This plugin [only works on desktop][1] because it has a strong dependency on Electron, which the Obsidian mobile app does not use.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/blob/master/manifest.json#L9
