### ISSUE TITLE
[BUG]  Can not edit template

### ISSUE THREAD

**Issue by zielperson** [hadynz/obsidian-kindle-plugin#157]
### Describe the bug
The template editor in settings is broken

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate the issue)

### To Reproduce
1. Go to 'Settings'
2. Click on the template text 
3. Try editing it

Here is a video:
https://www.awesomescreenshot.com/video/9083204

When the mouse moves over the text, I am trying to click on various points in the text to no avail.
You can see the text disappear when I press space.

### Expected behavior
I would expect this to behave like any text input.
However, I cannot place the cursor anywhere and hitting ANY key deletes the full template.

### Metadata
 - OS: Windows10
 - Plugin version 
 - Obsidian version 0.14.6

**Comment by hadynz** [comment]
@zielperson can you share the screenshot/video again. The attached link does not work and I cannot recreate the issue
