### ISSUE TITLE
Smarter file name template validation

### ISSUE THREAD

**Issue by adampick99** [hadynz/obsidian-kindle-plugin#164]
I decided to re-import my kindle highlights with a new template that I designed with Dataview in mind for the YAML front-matter. But after deleting the previous nodes created (all of them), I'm told that after attempting to import the clippings file again, the 'file already exists'. I can't think of any other local files that may be affecting this.

**Comment by hadynz** [comment]
> I'm told that after attempting to import the clippings file again, the 'file already exists'

How are you told that? In a pop-up?

Can you turn on your Developers tools, clear it, and then run the process again. If you share any error messages that you might be seeing it will help me troubleshoot your issue.

**Comment by adampick99** [comment]
![image](https://user-images.githubusercontent.com/78689653/172955245-ff7a372e-7ee8-4987-8b14-49ba5264923b.png)

This is the pop-up, and the developer console results

**Comment by hadynz** [comment]
`path="Books\BookHighlights\.md` looks suspiciously dodgy to me.

Did you customised the File Name template field? It is possible that the field does not have any unique field variables there (e.g. book title) and hence all your highlights are being overwritten to the one file.

Can you send me a screenshot/copy of your templates?

**Comment by adampick99** [comment]
Yeah it was the template formatting I had used, I've reverted it to the default and everything works fine now.

**Comment by hadynz** [comment]
Thanks for raising this.

I'll rename and keep this issue open. I think it would be good to add some safeguards to either prevent a bad template name to be used, or to show a more descriptive error message to the user.

**Comment by hadynz** [comment]
@adampick99  I haven't been able to recreate this issue at my end. Do you mind if you share the template you had which created this problem?
