### ISSUE TITLE
Amazon Session Security Question

### ISSUE THREAD

**Issue by pandichef** [hadynz/obsidian-kindle-plugin#167]
Regarding `logging in to your Amazon account via Obsidian your Amazon session becomes available to any other plugin across your vaults until your session expires`.

Thanks for pointing this out.  

Questions:
* Is there a spot on the Amazon site to revoke the access rights?  (If not, can you explain how I can find and delete the local session file?)
* Do the access right rights pertain on to Kindle Books, or to all associated Amazon/AWS accounts?

**Comment by hadynz** [comment]
Easiest way to think about this is to understand that the plugin mimics how you login to https://read.amazon.com/notebook to read your Kindle highlights. 

This means: 

- to revoke the plugin's access to your information you can (a) logout from the plugin, (b) change your Amazon password

- I believe Amazon have SSO. So you are logged into all of Amazon.com's services automatically

**Comment by pandichef** [comment]
I see.  Do you have a link that outlines the ideal workflow to export `my_clippings.txt` from [https://read.amazon.com/notebook](https://read.amazon.com/notebook)?

FWIW, it seems like Amazon & Kindle share a session, but AWS is a separate session (albeit the account ID is the same).

**Comment by hadynz** [comment]
> FWIW, it seems like Amazon & Kindle share a session, but AWS is a separate session (although the account ID is the same).

I believe that is accurate. AWS has different user and password than your amazon.com login. So I don't believe there is any risk/conflict with AWS.

> I see. Do you have a link that outlines the ideal workflow to export my_clippings.txt from https://read.amazon.com/notebook?

You don't export My Clippings.txt from read.amazon.com/notebook. This file is stored on the Kindle device. You will need to plug-in your kindle to your PC via USB cable, and then look for the file on the Kindle device.

**Comment by techdragon** [comment]
Is there any way to have the plugin limit the length of the session? Like a session timeout parameter? The .txt workflow is less than ideal but the security concerns about an unbounded length session token are also rather concerning given the potential financial impacts of malicious access to an account that lets you buy stuff with little friction.

**Comment by hadynz** [comment]
The plugin uses your Amazon login under the hood. So it is bound to their constraints. 

I can think of two solutions for people who are worried about this - which will still require you to trust this plugin doing its job under the hood:

1. Plugin always logs you out after every sync. It will require you to manually login before every sync
2. Plugin clears all sessions after every x number of hours periodically

Any thoughts on which of the above options would alleviate your fears?
