### ISSUE TITLE
[BUG] Cannot save "File template" when using nunjucks expressions

### ISSUE THREAD

**Issue by brpaz** [hadynz/obsidian-kindle-plugin#168]
### Describe the bug

When I try to customize the FIle template, the input box, gets a red border and doesn´t save even with the default template that I got from the source code. It works fine if I don´t use an nunjucks expressions like `{%`

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### To Reproduce
Steps to reproduce the behaviour:
Go to plugin settings and try to customize "File template" using nunjucks expressions

### Expected behaviour
The template should be saved correctly

### Screenshots
![Screenshot from 2022-06-16 16-11-02](https://user-images.githubusercontent.com/184563/174102005-8811827c-4290-45f4-b01c-0b4aa0c4a0f1.png)

### Metadata
 - OS: Linux Fedora 36
 - Plugin version 1.6.2
 - Obsidian version 0.14.15

**Comment by hadynz** [comment]
Can you share the exact template that you were trying to use, or a template that reproduces the issues please.

**Comment by brpaz** [comment]
I can reproduce the issue with the default template:

```
# {{title}}
## Metadata
{% trim %}
{% if authorUrl %}
* Author: [{{author}}]({{authorUrl}})
{% elif author %}
* Author: [[{{author}}]]
{% endif %}
{% if asin %}* ASIN: {{asin}}{% endif %}
{% if isbn %}* ISBN: {{isbn}}{% endif %}
{% if pages %}* Pages: {{pages}}{% endif %}
{% if publication %}* Publication: {{publication}}{% endif %}
{% if publisher %}* Publisher: {{publisher}}{% endif %}
{% if url %}* Reference: {{url}}{% endif %}
{% if appLink %}* [Kindle link]({{appLink}}){% endif %}
{% endtrim %}

## Highlights
{{highlights}}
``

**Comment by hadynz** [comment]
Thanks for sharing. Will check it out.

Do you care about the `trim` block? It is a custom block that I made to remove empty white lines. But I was thinking of removing it. Thoughts?

**Comment by brpaz** [comment]
not really.  I just wanted a base template to start defining my own and copied the one from the repository. I removed it and did my changes and it is looking fine for me.

**Comment by hadynz** [comment]
@brpaz I haven't been able to replicate this issue. Are you able to use the latest version and confirm that you are still getting the same problem please?
