### ISSUE TITLE
Author last name(s) as a variable

### ISSUE THREAD

**Issue by OogieM** [hadynz/obsidian-kindle-plugin#169]
**Is your feature request related to a problem? Please describe.**
I'd really like to be able to choose just the author's last name as the name field for the note title. 

**Describe the solution you'd like**
My preference for the note title format would be 
{{author_last_name}}-{{shortTitle}}-kindle

For books with 2 authors I could just accept the first author although I'd love it if it would work like Zotero and do the following:

{{first_author_last_name}}-{{second_author_last_name}}-{{shortTitle}}-kindle

For books with 3 or more authors
{{first_author_last_name}}_et_al-{{shortTitle}}-kindle

**Describe alternatives you've considered**
No real alternatives work. 

**Additional context**
Would keep my book notes consistent with my existing scientific paper notes and highlights.

**Comment by hadynz** [comment]
@OogieM I know this has been a long time coming, but your feature request has just been implemented in [1.7.0][1]. Would love it if you can give it a spin and let me know if it works for your workflow.

The plugin now can parse book authors and it breaks it down into a bunch of author variable names:

![image](https://user-images.githubusercontent.com/315585/188627679-6b3aff82-8929-46b7-a52f-8ff8ace5af66.png)

You can then specify the file name convention to use these variables:

![image](https://user-images.githubusercontent.com/315585/188628450-44e755ff-1529-40e9-8b28-bdf974bdbe2d.png)

The result will look something like this. Note - you will need to re-sync your books. I will be releasing a feature later on to make it easier to rename files in bulk.

![image](https://user-images.githubusercontent.com/315585/188628033-c098721e-9cc3-4340-9841-8a372e43360d.png)

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.7.0

**Comment by OogieM** [comment]
I haven’t been able to play with this yet.

Thank you!

> On Sep 6, 2022, at 5:55 AM, Hady Osman ***@***.***> wrote:
> 
> @OogieM I know this has been a long time coming, but your feature request has just been implemented in 1.7.0. Would love it if you can give it a spin and let me know if it works for your workflow.
> 
> 

Eugenie (Oogie) McGuire 
Desert Weyr, LLC - Hi Performance Black Welsh Mountain Sheep www.DesertWeyr.com
LambTracker - Open Source Flock Management Software www.LambTracker.com
Paonia, CO USA
