### ISSUE TITLE
Could you offer different login options for different countries?  

### ISSUE THREAD

**Issue by Shuusei04** [hadynz/obsidian-kindle-plugin#17]
I tried to log in with my amazon accounts(I own both Japanese and Chinese accounts), but I found that it seems only limited to support the American account. Would you offer other different countries options for us to log in to? The following website is offering people to switch different counties or regions accounts to login.
 
https://www.amazon.com/gp/navigation-country/select-country/ref=icp_lop_mop_chg_ais?ie=UTF8&preferencesReturnUrl=/

**Comment by hadynz** [comment]
Similar request to https://github.com/hadynz/obsidian-kindle-plugin/issues/6.

My understanding is a Chinese account cannot be supported as it doesn't have access to Amazon's https://read.amazon.com/notebook. However, a Japanese account could work.

If you can confirm that is the case (by accessing https://read.amazon.com/notebook under your Chinese and Japanese accounts), I can make a change in the plugin to support this feature.

**Comment by Shuusei04** [comment]
I can use another one  (https://read.amazon.co.jp/notebook) instead of this one (https://read.amazon.com/notebook).

**Comment by hadynz** [comment]
This has been implemented in the latest version of the plugin (v0.2.12). Give it a try and let me know if this works for you please.

**Comment by Shuusei04** [comment]
Cool!! It works very well for me now.
