### ISSUE TITLE
[BUG] Book names with [] in them Break Markdown links

### ISSUE THREAD

**Issue by talios** [hadynz/obsidian-kindle-plugin#170]
### Describe the bug

When importing highlights from books that include `[]` in them ( such as in my case, `Ricochet Joe [Kindle in Motion]`), you can't link to the actual file as the close brace causes the markdown links to end one character early.

### Method of syncing

- Amazon Kindle Reader
- My Clippings file (please **attach file** that can be used to recreate issue)

### To Reproduce

- Import the `My Clippings File` [My Clippings.txt](https://github.com/hadynz/obsidian-kindle-plugin/files/9076134/My.Clippings.txt)

- In another note, link to the page with `[[Ricochet Joe [Kindle in Motion]]]`
- Take note the third `]` doesn't appear as part of the link, and following it will create a new file.

### Expected behaviour

The linked page will open in Obsidian.

### Desired behaviour

Possibly rewrite the page title to `Ricochet Joe (Kindle in Motion)` to prevent breaking markdown.

### Metadata
 - OS: macOS
 - Plugin version 1.6.2
 - Obsidian version 0.14.15

**Comment by hadynz** [comment]
This has been implemented in [1.6.10][1]

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.6.10
