### ISSUE TITLE
[BUG]  Not Able to Update the Templates

### ISSUE THREAD

**Issue by mirkavolakova** [hadynz/obsidian-kindle-plugin#174]
### Describe the bug
I am not able to update the File or Highlight Templates. When I click in either of the fields, the cursor always displays at the very beginning of the text, and I'm not able to work with the text in any way (e.g. select it by my mouse or write anything).

You can see that I'm using a custom theme, however, this doesn't affect this issue (I tried switching to the default and the bug was still persisting).

### Method of syncing
- [ ] Amazon Kindle Reader
- [x] My Clippings file

### To Reproduce
Steps to reproduce the behaviour:
1. Open the plugin settings
2. Click in either the File Template or HIghlight Template input field
3. Try editing the template text

### Expected behaviour
I should be able to edit the text within both the File Template and the Highlight template input fields.

### Screenshots
![image](https://user-images.githubusercontent.com/3714529/180139409-bd258b9f-37da-4271-ad46-922ba90f45fe.png)

### Metadata
 - OS: macOS 12.0.1
 - Plugin version: 1.6.3
 - Obsidian version: Version 0.15.6 (installer 0.14.15)

**Comment by Fabian3178** [comment]
I have the same problem!

**Comment by intrnal** [comment]
Same problem but on windows.

**Comment by hadynz** [comment]
Can you please see if this issue still exists in the latest version of the plugin 1.8.0 which was released this morning?

I've build a brand new template editor to make it easier for users to customise and preview their templates to their liking.

I haven't experienced this issue with this latest version.
