### ISSUE TITLE
[Feature Request] Synchronize additional book metadata (% Read, Total Pages, etc)

### ISSUE THREAD

**Issue by evitiello** [hadynz/obsidian-kindle-plugin#176]
**Describe the solution you'd like**

I would love if the % complete, total pages in the book, total pages read, etc were also synced and added to the page metadata.

**Comment by hadynz** [comment]
HI @evitiello. In terms of your suggestion:

Already exists:
* Total pages in book - the plugin makes this data available if its a book purchased from Amazon

No possible known way - there is no way that the Kindle or Amazon exposes this information:
* % complete
* Total pages read

**Comment by evitiello** [comment]
Gotcha, thank you!
