### ISSUE TITLE
Sync only my highlights/notes?

### ISSUE THREAD

**Issue by PolymathCrowsbane** [hadynz/obsidian-kindle-plugin#177]
Currently, when highlights are synced, they include highlights from other readers. While some are insightful, I would prefer to see only my own notes and highlights in Obsidian. Would it be possible to sync only my own notes/highlights? Ideally, there could be an option to sync all or only mine. Of course, it may be that the Amazon APIs don't allow this degree of granularity.

Thanks for a great plug-in,
Robert

**Comment by hadynz** [comment]
> Currently, when highlights are synced, they include highlights from other readers.

That's the first time that I hear about this. My understanding and observation are that all the highlights and notes are always based on your activity.

Can you send me some screenshots and examples of highlights from other readers coming into your vault, please? It would be interesting to learn about this.
