### ISSUE TITLE
[BUG]  Failed to load plugin manifest

### ISSUE THREAD

**Issue by bummings** [hadynz/obsidian-kindle-plugin#185]
### Describe the bug
Receiving `Failed to load plugin manifest` upon attempt to open the plug-in via the community plug-ins browser.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to preferences
2. Click on `Community plugins`
3. Click on `Browse`
4. Search for `Kindle Highlights`
5. Click on `Kindle Highlights`

### Expected behaviour
An error displays "_Failed to load plugin manifest_"

### Screenshots
<img width="959" alt="Screen Shot 2022-08-26 at 11 28 39 AM" src="https://user-images.githubusercontent.com/34618112/186940060-46ba51ef-f255-49a4-96ee-3534602a5238.png">

### Metadata
 - OS: MacOS 12.5
 - Obsidian version 0.15.9

**Comment by hadynz** [comment]
Thanks for raising this! I made a change last night with how the plugin generates manifest and looks like it is not working as expected.

Looking to resolve and fix now

**Comment by hadynz** [comment]
Fixed!
