### ISSUE TITLE
Avoid highlight splitting when is between two pages

### ISSUE THREAD

**Issue by bdalia** [hadynz/obsidian-kindle-plugin#195]
I noticed that some highlights are split in two because they happens between two pages/locations.

Is there a way to avoid this?

It may be very useful if the plug-in catch this condition and generate one hilight instead of two.

Thank you very much for this great plug-in

Here is an example of the case for one of my books:

Un mercato consiste nell’insieme di tutti i clienti – attuali e potenziali – che possono cercare e comprare prodotti e servizi per uno — location: [1063](kindle://book?action=open&asin=B0897PP9LZ&location=1063) ^ref-14057

---
specifico caso d’uso secondo una domanda pre-esistente. — location: [1064](kindle://book?action=open&asin=B0897PP9LZ&location=1064) ^ref-18528

**Comment by hadynz** [comment]
Thanks for raising this issue @bdalia. I never noticed that this was happening myself.

What's difficult about the solution you are proposing is that there is no way that the plugin can know if two separate highlights are actually one and happen to be separated because they exist between two separate pages or locations.

Do you know why the Kindle separates such a highlight into two? If you can share some screenshots and more examples that would be very helpful to understand when/how this behaviour occurs in order to look at solution options.

**Comment by rviljoen** [comment]
@bdalia On my Kindle (Oasis), I am able to create a single highlight that spans two pages. The UI is a bit clunky, but it does work. You need to highlight to the bottom of the page, hold it for a second or so and then it will flip to the next page where you can select the end point. Bit finicky, but it does work to create a single highlight.

**Comment by bdalia** [comment]
> @bdalia On my Kindle (Oasis), I am able to create a single highlight that spans two pages. The UI is a bit clunky, but it does work. You need to highlight to the bottom of the page, hold it for a second or so and then it will flip to the next page where you can select the end point. Bit finicky, but it does work to create a single highlight. 

Thank you very much for this Tip. I own a kindle oasis too, so i will try it.

Recently I use to read kindle books also on my iPad. With it there are no probs because with continuous scrolling i can take highlights in a very comfortable way.

Regards

**Comment by hadynz** [comment]
As @rviljoen mentioned, holding down a highlight at the bottom of a Kindle page, will flip to the next page and continue the highlight. 

I didn't realise that you didn't know this technique.

Now that you've found a way for this, will assume this is a non issue and it can be closed.
