### ISSUE TITLE
Add option for myclipping.txt

### ISSUE THREAD

**Issue by trungng2006** [hadynz/obsidian-kindle-plugin#2]
Thank you for the plugin, but may I ask would it be possible to add an option for processing myclipping.txt from kindle instead of having to login the amazon account?

**Comment by hadynz** [comment]
May I ask what is the use case that sees a user prefer to upload (?) their "My Clippings.txt" instead of logging with their Amazon login without the need for a physical Kindle to always be around?

**Comment by trungng2006** [comment]
Thank you for your quick reply.
Usually when i plugin my kindle to the computer side load new books, then i also copy myclipping.txt out. This help keep my highlights in my computer instead of having to log into amazon each time.
Because I use this process, I almost never connect my kindle to wifi, so myclipping.txt is not sync to Amazon database.

**Comment by hadynz** [comment]
Got it. I had a read online to understand why many people gravitate to extracting their highlights through a physical connection to their Kindle. I think as you alluded to it, often people will use the Kindle to read material that is not on Amazon (e.g. side loaded books, articles, etc) and hence they won't be able to see any highlights on Amazon even if they logged in.

Makes so much sense. I will happily add this to the roadmap of the plugin. I'll leave this thread open and update you when I get this feature done.

**Comment by trungng2006** [comment]
Thank you so much!

**Comment by andrezgz** [comment]
I would love to see this feature added too! As it has been mentioned I use the Kindle to read content not available on Amazon. Nowadays I’m processing myclippings.txt with an awk script to make the md file for each book.

**Comment by hadynz** [comment]
I should have it done by the end of the week. I already have a working prototype. Just need to make sure that I address some known edge cases in the workflow.

**Comment by danieltomasz** [comment]
Yes, possibility to use myclippings would be great! Many countries doesn't have amazon ebook-store in their language, I for example prefer-side load my books through calibre rather  than sending them through email to amazon.

**Comment by EhuddR** [comment]
Wow! i just want to say that if you would add this functionality it would help me a lot because as many comments say not all of us use books directly from amazon on kindle. I was looking for a way to accomplish this all last week however several scripts i tried did not work correctly. I will keep an eye out for the next versions of your plugin. 

Best regards.

**Comment by hadynz** [comment]
Just implemented the requested feature of supporting upload of `My Clippings.txt` file as part of [0.1.0][1] release.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.1.0

**Comment by trungng2006** [comment]
Thank you for implementing this feature!!!
Could you help guide me how to upload the Clipping.txt to Obsidian?

**Comment by trungng2006** [comment]
> 
> 
> Thank you for implementing this feature!!!
> Could you please help guide me how to upload the Clipping.txt to Obsidian?

nvm. i got it. click on the status bar.
Thank you!

**Comment by andrezgz** [comment]
Today I've processed my clippings file and it worked like a charm!

Thanks a lot!
