### ISSUE TITLE
Please add support for Amazon website in Chinese!

### ISSUE THREAD

**Issue by ProudBenzene** [hadynz/obsidian-kindle-plugin#207]
I am a Chinese Kindle User and I have tried the _global_ one, and ended up in vain.
![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/202210171210727.png)
I am convinced that many of the users of the plugin is from China, so it is necessary to add support for the Chinese website: Amazon.cn.

Last but not least, thank you for your developing for people who love reading!

**Comment by hadynz** [comment]
Can you confirm that your books are accessible on this URL please: https://read.amazon.cn/notebook

**Comment by hadynz** [comment]
I believe this is a show stopper.

The plugin's cloud sync works by accessing Amazon's online Kindle Reader and scraping the HTML. Checkout the following screenshot to see what that read looks like.

![image](https://user-images.githubusercontent.com/315585/201202350-995073a0-12b8-447f-a711-c0e551577684.png)

It seems that Amazon does not have such an experience available for Chinese users. I just had a read online and there are several news reporting that Kindle books are [no longer available in China as of this year][1]. 

Your other option hence is to sync your highlights using the My Clippings file on the device using a USB cable.

[1]: https://www.reuters.com/technology/amazon-says-will-shut-kindle-bookstore-china-next-year-2022-06-02/

**Comment by ProudBenzene** [comment]
It's a real shame, but thanks for your work! Maybe Amazon didn't offer this kind of online note viewing solution for Chinese users from the beginning 🥲
