### ISSUE TITLE
[BUG] highlight createdDate returning as today's date

### ISSUE THREAD

**Issue by jamesvclements** [hadynz/obsidian-kindle-plugin#210]
### Describe the bug
`createdDate` doesn't exist on highlights:

![How to Win Friends and Influence People (Dale Carnegie) - main - Obsidian v1 0 0-Monday-October-24-2022-09 47 05AM@2x](https://user-images.githubusercontent.com/20052710/197580854-2aead97b-3c6b-4705-866f-0cfe9815cb44.png)

![How to Win Friends and Influence People (Dale Carnegie) - main - Obsidian v1 0 0-Monday-October-24-2022-09 47 27AM@2x](https://user-images.githubusercontent.com/20052710/197580913-2269b250-b6af-4592-8244-d1d4c7919d4a.png)

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### Metadata
 - OS: [e.g. Mac, Windows, Linux]
 - Plugin version [e.g. 1.5.2]
 - Obsidian version [e.g. 1.0.0]

**Comment by jamesvclements** [comment]
Is this only available when using clippings.txt? I'm not certain I see the highlight date in the web page I think is being scraped:

![Kindle Your Notes and Highlights-Monday-October-24-2022-09 50 21AM@2x](https://user-images.githubusercontent.com/20052710/197581606-560b0225-d2b7-46ba-bea0-e21085bf5f95.png)

**Comment by tonyxiao** [comment]
@jamesvclements Readwise's extension is able to get it somehow. I tested and it works appropriately as the highlighted date (though not 100% available)
![CleanShot 2022-11-03 at 12 58 32@2x](https://user-images.githubusercontent.com/696842/199714947-c903bb59-ee61-4337-9fa9-4b26025f4c1e.png)

**Comment by tonyxiao** [comment]
This is the #1 reason preventing me from switching to this plugin from readwise (prefer this plugin as I often read on the iPad and readwise requires me to be on my computer with browser open for the sync to work...)

**Comment by hadynz** [comment]
A clipping's highlight date time exists in the My Clippings file. But I have not been able to find it in the online Kindle Reader page, meaning the information is not available for the plugin to scrape.

I am surprised that Readwise has this field available!

**Comment by tonyxiao** [comment]
Maybe give it a try via readwise and you can identify a book that has the right highlight dates. As not all books have them.

**Comment by hadynz** [comment]
@tonyxiao I have a good amount of books in my Kindle library and haven't run into an example were the created dates were visible in the online Kindle Reader.

It seems you have found one such example. Do you mind that for the book that Readwise shows highlight date that you go to the Kindle Reader and inspect the DOM to see where these dates are visible? That would help me a lot. 

At the moment I simply cannot recreate this.

**Comment by hadynz** [comment]
I just pulled out [Readwise's chrome extension code][1] and went through to see how they scraped creation date of highlights. They simply don't have that logic in their extension, meaning that that these dates must come from another source (Kindle Clippings?).

I don't believe that this feature is possible.

[1]: https://github.com/hadynz/readwise-chrome-extension/blob/master/src/bg/background.js

**Comment by hadynz** [comment]
That's right. The only available date that we know is when a book was last accessed. Annotating highlights with that date is inaccurate. However, it can be accurate if someone has a habit of syncing their highlights on a daily basis - which might be the big assumption that Readwise is making. This plugin has that date and makes it available to use in any of its templates. So you can get the same result.

The Kindle Clippings file does have the created date for a highlight available and the plugin will use it correctly.

**Comment by tonyxiao** [comment]
Hmm i think you are right, it might be the `lastAccessed` date. As all my `highlight_date` are the same despite the fact that I highlighted them on different days.

**Comment by jamesvclements** [comment]
@hadynz that's a good point, last accessed becomes useful if you're syncing every day.

In this case, could you add `lastAnnotatedDate`` to the highlight template variables?
![How to Win Friends and Influence People (Dale Carnegie) - main - Obsidian v1 0 3-Thursday-November-10-2022-11 42 24AM@2x](https://user-images.githubusercontent.com/20052710/201190937-f8828d0a-e179-4a73-9a1a-bc772d7faae5.png)

**Comment by jamesvclements** [comment]
@hadynz that's a great point that last accessed becomes useful if synced everyday.

Could you add `lastAnnotatedDate` as a variable for the highlight template?

![Company Of One (Paul Jarvis) - main - Obsidian v1 0 3-Thursday-November-10-2022-11 45 39AM@2x](https://user-images.githubusercontent.com/20052710/201191622-9b3242e9-f743-412e-8f64-286172a515b5.png)

**Comment by hadynz** [comment]
I'll make an update to make the variable available in the highlight template and update this thread when it's complete

**Comment by tonyxiao** [comment]
By tge way is there a way to get clippings.txt without a kindle device handy?

**Comment by hadynz** [comment]
> By tge way is there a way to get clippings.txt without a kindle device handy?

No, that's not possible. It is a physical file that is stored and updated on the Kindle device as you use the device.

**Comment by tonyxiao** [comment]
I see. Do you know if it contains only the highlights you made on that device or all highlights from your entire kindle account?

**Comment by hadynz** [comment]
Only highlights made on this specific device.
