### ISSUE TITLE
[BUG] Highlight template: `if` statements with equality expression don't work

### ISSUE THREAD

**Issue by lukebarton** [hadynz/obsidian-kindle-plugin#214]
### Describe the bug
If statements in highlights cause an error when syncing highlights.

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### To Reproduce
Steps to reproduce the behaviour:
Highlight template: ```{% if color == "yellow" %}I am yellow{% endif %}```

### Expected behaviour
Expected if statement to test if color equals "yellow" and output "I am yellow"

### Metadata
 - OS: Mac
 - Plugin version 1.7.0
 - Obsidian version v1.0.3

**Comment by hadynz** [comment]
@lukebarton I am not able to reproduce the error that you speak about.

I've just modified the highlight template and added your if-statement and it works as expected.

![image](https://user-images.githubusercontent.com/315585/200805469-f81399f1-1c21-4f44-b636-fa906f3d690d.png)

Can you try with the latest version of the plugin please while you are at it (1.8.0)?

**Comment by lukebarton** [comment]
Works in 1.8.0
