### ISSUE TITLE
Support amazon.com.br

### ISSUE THREAD

**Issue by FabianoLothor** [hadynz/obsidian-kindle-plugin#224]
I'd like to ask to add support to amazon.com.br if possible.

**Comment by hadynz** [comment]
Can you confirm if you are able to access your purchased books from Amazon on https://read.amazon.com/notebook?

**Comment by FabianoLothor** [comment]
Hi friend, I tried to use the library connecting via `amazon.com` earlier today and did work.

I'm closing this thread here. Sorry about that.
