### ISSUE TITLE
Jump to location in Kindle Reader

### ISSUE THREAD

**Issue by rtm** [hadynz/obsidian-kindle-plugin#227]
The Amazon notes & highlights viewer at read.amazon.com/kp/notebook has a little dropdown next to each note giving you the option to jump to that location in the book in Amazon cloud reader. Would it be possible to add an option to include such a link in each imported note or highlight?

**Comment by elifiner** [comment]
Every highlight already has such a link - the location number at the end of each highlight links to a `kindle://` URL that opens the mobile Kindle app at the right spot. Does it work when you click it?

**Comment by hadynz** [comment]
Thanks for answering @elifiner. That's correct. The "jump to location" link is already available as a template variable (`appLink`) that you can use in your template.

![image](https://user-images.githubusercontent.com/315585/229636410-6caa0ad5-62f6-490d-8de8-5c45d23212d5.png)

**Comment by TomYeoman** [comment]
How do I actually open this, in for example caliber?  When I click on the link it just attempts to create a page

![image](https://github.com/hadynz/obsidian-kindle-plugin/assets/14075632/24680047-5ae1-4af4-8871-407c4294d87b)

**Comment by euler007** [comment]
I have the same issue where {{appLink}} is empty and therefore it attempts to create a new page
