### ISSUE TITLE
Book covers with metadata

### ISSUE THREAD

**Issue by ceselder** [hadynz/obsidian-kindle-plugin#231]
I think it would be neat to have covers for the book as metadata like in the image attached.

Could be a toggle in obsidian settings too.

Images would not need to be stored in obsidian itself since there are plenty book cover APIs.

![image](https://user-images.githubusercontent.com/94973748/210661987-3078398a-af1c-4d4a-8684-e83be08c8033.png)

**Comment by ceselder** [comment]
Is anyone else interested in this? Might just do it myself tommorow

**Comment by hadynz** [comment]
@ceselder this is something that you can easily do by modifying your notes template

![image](https://user-images.githubusercontent.com/315585/227751764-616c84fc-85e0-48a9-ac36-8aba08f4e331.png)

Simply add the following:

```
![]({{imageUrl}})
```

If you want more control with the image size, then your next best bet is to use an HTML image tag `<img src="{{imageUrl}}" width="200px"/>`.

**Comment by ceselder** [comment]
Oh my bad!

**Comment by jimclay75051** [comment]
I would love to have the covers.

I tried ' ![]({{imageUrl}}) ' and it did not work for me.

**Comment by hadynz** [comment]
@jimclay75051 what the output of that markup?

**Comment by jimclay75051** [comment]
I'm quite possible not doing it correctly.

![image](https://user-images.githubusercontent.com/30031026/227813441-c0130e1d-fc99-4a5c-9ca4-3f0ab7bb9d6d.png)

Basically, it doesn't do anything.

**Comment by hadynz** [comment]
@jimclay75051 You need to add `![]({{imageUrl}})` to your "template" and not an existing note that has already been generated.

You need to go to Kindle Highlight's settings -> Manage Template and then modify the Content template.

After that is done, you will need to regenerate your existing notes. Best way is to delete your existing notes and sync again.

If you do not want to delete your existing notes, you will need to manually add the image link yourself. You should see the book image link available in the frontmatter.

**Comment by jimclay75051** [comment]
You are correct. That worked. Thank you.
