### ISSUE TITLE
Longer highlights are trimmed 

### ISSUE THREAD

**Issue by Maurilio97-P** [hadynz/obsidian-kindle-plugin#232]
For example, I have a long highlight like:

"This is a long quote from the author and I wanna copy this long sentence"

And in Obsidian all I see is:

"This is a long quote from the..."

**Comment by italosvieira** [comment]
https://github.com/hadynz/obsidian-kindle-plugin#export-limits

Export limits

For several reasons (see [here](https://help.readwise.io/article/47-why-are-my-kindle-highlights-truncated-ellipses#:~:text=Publishers%20require%20Amazon%20to%20place,the%20book%20will%20be%20truncated.) and [here](https://brian.carnell.com/articles/2018/route-around-amazon-kindles-ridiculous-limits-on-highlights-exporting-with-bookcision/)) the Kindle platform can sometimes limit the amount of highlighted text that can be exported from a particular book. This limit varies from book to book, purchased from Amazon or have DRM protection. There is currently no known alternative to work around this.

**Comment by hadynz** [comment]
Thanks for responding to this question @italosvieira. 

@Maurilio97-P this is currently a limitation by Amazon and I don't believe there is any workaround for it.
