### ISSUE TITLE
Notes area

### ISSUE THREAD

**Issue by ProudBenzene** [hadynz/obsidian-kindle-plugin#247]
Hello! I've got an idea that can greatly expand the usefulness.

I hope it is possible to automatically generate a section at the top of the markdown file generated after importing Kindle highlights, and the content in this area will remain unchanged for future imports, where users can write their thoughts about the book. I believe this will also increase the chance for users to look through their Kindle highlights, and I think it will be more convenient for users to check the tips and highlights in one file.

This is a personal idea of mine about plugin enhancements, if you think this idea is immature or inappropriate, please feel free to reject it.🥰Thanks for all the work you put into this plugin!

**Comment by hadynz** [comment]
The best solutions always start with from a spontaneous or simple idea.

I believe what you are asking for is currently supported by the plugin.

When you re-sync your highlights for a given book, the plugin actually does a "diff" to figure out (a) what new highlights have been made, (b) where to insert them. It is for this reason that the plugin generates highlights with a reference id (e.g. `^ref-12312`. That's what the plugin uses to identify which highlight is which.

Try it out for yourself now and let me know if what's implemented will work for the workflow you have in mind.

**Comment by ProudBenzene** [comment]
I just tried it and it does exactly what you said and fits my needs perfectly! I will close this issue!

**Comment by hadynz** [comment]
Glad to hear that's the case!
