### ISSUE TITLE
[BUG] Notes on docs files do not sync

### ISSUE THREAD

**Issue by henryhund** [hadynz/obsidian-kindle-plugin#250]
### Describe the bug
Notes on docs files do not sync

### Method of syncing
- [x] Amazon Kindle Reader
- [ ] My Clippings file (please **attach file** that can be used to recreate issue)

### To Reproduce
Steps to reproduce the behaviour:
1. Open a docs file on kindle (not a book, but a docs file)
2. Create highlights
3. Sync Obsidian
4. The Docs file doesn't create notes

### Expected behaviour
I expected all notes on all file types that I take on my kindle to sync.

### Screenshots
I don't think a screenshot is needed.

### Metadata
 - OS: macOS Monterey 12.6
 - Plugin version = 1.9.2
 - Obsidian version = 1.1.16

**Comment by hadynz** [comment]
@henryhund The plugin offers two methods of thinking:

1. Amazon cloud - the only highlights and notes saved on the cloud are for books purchased from Amazon.com
2. My Clippings - this is a physical file that lives on your device. Any book or document, regardless of origin of purchase, will have its highlights and notes in that file

Given your use case, your only option is to connect your Kindle to your machine with a USB Drive, find the My Clippings file on the device, and then load this file via the plugin.

If that doesn't work, share with me any more/new information and I can re-open this issue.
