### ISSUE TITLE
Please add support for the Australian Kindle highlights

### ISSUE THREAD

**Issue by derrickwheals** [hadynz/obsidian-kindle-plugin#255]
**Is your feature request related to a problem? Please describe.**
Currently there doesn't appear to be support if you have an Australian Amazon account

**Describe the solution you'd like**
Add support for https://read.amazon.com.au/notebook

**Describe alternatives you've considered**
I looked in the plug-in settings and Australia is not listed

**Additional context**
none

**Comment by derrickwheals** [comment]
I have since tested with the US store and it seems to work even though my account is AU.

**Comment by hadynz** [comment]
Global Amazon should work for most countries around the world including Australia.
