### ISSUE TITLE
Allow ability to move notes to a different directory without resyncing

### ISSUE THREAD

**Issue by justindirose** [hadynz/obsidian-kindle-plugin#29]
Currently, if you move a book note out of the selected directory, the next time sync runs, you get a full sync.

Unfortunately this is a bit problematic, as there are some book notes I keep in a private folder that I don't publish, and others I already have pulled in via other methods that I don't want duplication.

It would be great if there was a tag or YAML metadata field the plugin checks to sync up titles, or something of that sort.

**Comment by hadynz** [comment]
Noted as a really good feature to add to the plugin.

I'll add it to the roadmap and let you know when it is implemented.

**Comment by hadynz** [comment]
I know this has been a long time coming... but this feature is not finally available as of [v1.0.0][1].

The plugin now uses frontmatter at the top of every file to store state information. This has allowed for a user to move a file to any directory in the vault that they would like. The plugin is still aware of the highlights file and will factor that into account with any future sync and resync.


[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.0.0
