### ISSUE TITLE
Contents of title and highlights escaped

### ISSUE THREAD

**Issue by apollooakwood** [hadynz/obsidian-kindle-plugin#3]
In the output of some tags, some of the content is escaped where it probably shouldn't be (or doesn't need to be). Example:

{{title}}: A book title that should show as ``Cabins & Cottages, Revised & Expanded Edition`` shows as ``Cabins &amp; Cottages, Revised &amp; Expanded Edition``.
{{author}}: An author that should show as ``America's Test Kitchen`` shows as ``America&#39;s Test Kitchen``.
{{highlight.text}}: A highlight that should read ``Plant in spring & summer`` shows as ``Plant in spring &amp; summer``

I tried doing {{title | safe}} after poking through the nunjucks documentation, but it doesn't seem to work.

**Comment by hadynz** [comment]
This fix has been bundled as part of release [0.0.7](https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.0.7).
