### ISSUE TITLE
Always "starting sync" on mac and failing to load on Mobile

### ISSUE THREAD

**Issue by zzdcgg** [hadynz/obsidian-kindle-plugin#30]
Hi @hadynz, I had the following issues, not sure if you have any fix...

On Mac - tried to sync "My Clippings.txt", but the bottom bar always showed "starting sync" with no progress (see the screenshot);

On Mobile - every time I started the mobile app, it said "failed to lead the kindle plugin".

Any help is much appreciated.  Thanks!

![image](https://user-images.githubusercontent.com/70086177/117767964-3f18dd80-b264-11eb-95c9-3f61b6d495af.png)
![image](https://user-images.githubusercontent.com/70086177/117767979-42ac6480-b264-11eb-8818-1227982a1750.png)

**Comment by hadynz** [comment]
@zzdcgg the plugin has probably crashed whilst trying to parse your `My Clippings.txt` file. I need to improve the error reporting of the plugin. In the meantime, if you turn on the Developer Tools and look at the Console, you should see an error being printed.

Easiest way if you don't mind, is to send me your Clippings file (hadyos@gmail.com). I can load it and see what is failing and make a fix. Amazon does not publish a spec for how they format `My Clippings`. So unfortunately, currently it is a process of adding every permutation that different users encounter.

Lastly - the plugin was never tested in mobile. It is dependent on Electron being present. I haven't kept up with how Obsidian's mobile app is designed, but I doubt they have an abstraction for Electron. For now, the app is for desktop only.

**Comment by zzdcgg** [comment]
It worked with the new update.  Thanks @hadynz!
