### ISSUE TITLE
Sync stopped working

### ISSUE THREAD

**Issue by mpazaryna** [hadynz/obsidian-kindle-plugin#31]
This awesome plugin was working just fine for about a week.  Suddenly, the sync stopped fetching any updates.  Interestingly enough, when it attempts to sync now, I see on the Obsidian screen two titles display, that I don't have in my kindle library.  

I have reinstalled the plugin several times.

**Comment by mpazaryna** [comment]
Hello,  I went through and made several updates to a Kindle book (using my iPad) and navigated over to Obsidian to see the changes.  I click on the status bar in Obsidian and launch the sync process.  I consistently am shown two titles in the update dialog screen that I don't own.  I did check my Amazon account and they're not a part of my list.  One is "Pride and Prejudice" and the other is "Wall Street and the Financial Crisis".  These two always come through.  However, any of the updates that have been made, and I've tested on two different titles, does not appear.  It seems as if the initial collection of the 78 titles I have in Kindle was successful, but updates are not happening.  I am syncing from the cloud, not the local file.  Thanks.

**Comment by hadynz** [comment]
It sounds like you are referring to two different issues:

#### Re-syncing 
Currently the plug-in will only a book once regardless of changes we we l in highlights. I will be changing this behaviour soon. For now, you will need to delete any book that you want rescynced first. Running a sync will recreate it with all your latest highlights. 

#### Unexpected data in sync 
The plug-in fetches your data from https://read.amazon.com/notebook. Can you login to that portal and verify that the two books in question are **not** listed there.

**Comment by mpazaryna** [comment]
Thanks so much for the help, my misunderstanding.  I do find this plug in to be very useful and having it update will be perfect.  On the second item, I did find them and they are there without any highlights, it's been so long I forgot about them.  I'm closing this issue.  Thank you for your support and work on the plugin.  Matt

**Comment by mpazaryna** [comment]
See above comment.
