### ISSUE TITLE
Show errors visually

### ISSUE THREAD

**Issue by AblingerOscar** [hadynz/obsidian-kindle-plugin#34]
I made an error in my template (forgot a `}}`) and at first thought the plugin just wouldn't work.

The dev console told me that the parsing failed and looking over it, I found the error.
Many people will not know to look there, though.

So a toast or something that tells you that there was an error (best case what kind of error) would probably be useful.

**Comment by hadynz** [comment]
Thanks for raising this. This scenario occurred to me, but I never tracked it.

It is a valid issue, and one that should be resolved.

I am thinking of doing the following:

1. On every update to the template, the plugin validates if the template syntax is valid nunjucks
2. If it is valid, then template change is saved
3. If it is invalid, then change is not saved, the template textarea is marked in error (border is red)

A toast IMO is not ideal. Obsidian's settings paradigm works by auto-saving. A user might be in the middle of typing a change, and continously showing them an error toast might not be the best experience.

Let me know what you think of my above suggestion.

**Comment by AblingerOscar** [comment]
I'm not that familiar with nunjucks (haven't heard it until I started using this plugin) so if that's easily possible, that sounds like a good solution.
I might even go that far to save it, but still use the last valid one (that way, I could close the setting, look something up in one of my notes and then return into the setting), but that's not absolutely necessary.

I also didn't mean that the toast should appear when you insert the template, rather when you're trying to import books.
Currently, without looking at the dev console, it's indistinguishable whether the template is invalid or whether there just weren't any books to synchronise.
So just an error that the synchronisation of a book failed would solve that.
And a notification if something went wrong should not only happen for when the template is wrong, but in general – I don't know if all other options are covered, but a generic `try-catch` might still be a good idea.

**Comment by hadynz** [comment]
This has been fixed and released in version 0.2.10.
