### ISSUE TITLE
Error in parsing My Clippings.txt

### ISSUE THREAD

**Issue by onepointfivem** [hadynz/obsidian-kindle-plugin#35]
I'm getting a strange error when trying to load the plugin.

Steps to reproduce the error:
1. Download and activate plugin
2. Run through command pallet, choose My Clippings.txt from folder

I haven`t touched anything on the plugins settings page. I have many highlights from portuguese books.
[My Clippings.txt](https://github.com/hadynz/obsidian-kindle-plugin/files/6480651/My.Clippings.txt)

I attached my clippings.txt file
```
VM164:2 Could not parse entry in clippings file n {_bookTitleAndAuthors: "Garota exemplar (Flynn, Gillian)", _contentClipp: "Na verdade, queria que ela lesse minha mente para …er de me rebaixar à arte feminina da articulação.", _metdataClipp: "- Seu destaque ou posição 2829-2829 | Adicionado: sexta-feira, 29 de novembro de 2019 18:00:13"}
eval @ VM164:2
t.parseKindleEntries @ VM164:2
eval @ VM164:2
startSync @ VM164:2
async function (async)
startSync @ VM164:2
onMyClippingsSync @ VM164:2
onClick @ VM164:2
eval @ VM164:2
VM164:2 Error parsing C:\Users\camil\Google Drive\3 Referências\Kindle\My Clippings.txt. Error: Error: Couldn't parse type of Entry: pageMetadataStr: - Seu destaque ou posição 2829-2829
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:4641)
    at Array.forEach (<anonymous>)
    at Object.t.parseKindleEntries (eval at <anonymous> (app.js:1), <anonymous>:2:4515)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:489993)
    at Dt.startSync (eval at <anonymous> (app.js:1), <anonymous>:2:490066)
startSync @ VM164:2
async function (async)
startSync @ VM164:2
onMyClippingsSync @ VM164:2
onClick @ VM164:2
eval @ VM164:2
```

**Comment by hadynz** [comment]
Thanks for sharing. 

I believe you are getting this message because your My Clippings file is in a language (Spanish?) that is not supported.

Can you send me your original file to hadyos@gmail.com. I will update the plugin to support your language too.

**Comment by hadynz** [comment]
Thanks for sending through your email and file. 

Your data is in Portuguese which is currently not supported by the plugin. That is a straight forward change that I can make though. I'll pick this up over my weekend in NZ and let you know here when it is done.

**Comment by hadynz** [comment]
The latest version of the plugin ([v0.2.13][1]) that I just published should resolve your issue now. 

Try it now and let me know so we can close the issue. 

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.2.13
