### ISSUE TITLE
Adding Color to highlight extraction

### ISSUE THREAD

**Issue by BradenKoh27** [hadynz/obsidian-kindle-plugin#36]
Hi there, 

just wanted to say that I love this plugin and thanks for your work on this. 

I added a bit of code on my own to also pull out the colour of the highlights from Amazon.

I am fairly new to Github, so I had trouble trying to submit my code in a new branch and making a pull request for that branch.

But I just made the adjustments here:

in "scrapeBookHighlight.ts", I added :

`color : $('#annotationHighlightHeader', highlightEl).text().split(' ')[0]` at line 19-20

to the `parseHighlights` function.

Then I added `color` to the respective nunJucks model 

```
export type Highlight = {
  id?: string;
  text: string;
  location?: string;
  page?: string;
  note?: string;
  color? : string;
};
```

Hope that was alright. 

Thanks

**Comment by owenvachell** [comment]
I'd also find this useful. Added to [pull request](https://github.com/hadynz/obsidian-kindle-plugin/pull/37)

**Comment by hadynz** [comment]
Thanks so much @BradenKoh27 for the suggestion and @owenvachell for the PR implementation. Hopefully we will have it merged and added to the plugin soon

**Comment by BradenKoh27** [comment]
Thank guys. @owenvachell @hadynz. Again, just great work on the plugin. It's awesome.

**Comment by hadynz** [comment]
Sorry for taking time to release your work @owenvachell.

Your change has just been released in the latest version.
