### ISSUE TITLE
Cant  sync new  notes for the same book 

### ISSUE THREAD

**Issue by rbb428** [hadynz/obsidian-kindle-plugin#38]
I found I can't synced new notes if I have already synced the same  book with some old notes in the obsidian. I am not sure if it has the features to sync new change of a book. In addition I found the reset function is not working. I got like 144 books synced, however I only have 9 books. I have synced 16 times so I got 144 books synced . This notification is kind of weird.

**Comment by hadynz** [comment]
Thanks for raising this issue.

At the moment the plugin has a very rudimentary method of syncing. If a book has been synced before, it will never attempt to resync it even if new highlights are found. This was a simple implementation as modifying an existing file with highlights can be difficult - no guarantee that the file hasn't been modified by a user after sync.

I plan to introduce some more options for users to decide how resync can work for them. You can join the discussion on this feature here https://github.com/hadynz/obsidian-kindle-plugin/discussions/27. I will be working on this as enhancement at some point shortly as IMO it is required for the plugin to be fully fledged for most users.

**Comment by rbb428** [comment]
Thanks! Looking forward to the new update.

**Comment by hadynz** [comment]
Resyncing has finally been implemented as of [v1.0.0][1].

It is however a breaking change. You will need to run the plugin and get it to sync all your files again. This is required for two reasons:

(a) the plugin now uses frontmatter that it adds to the top of very file
(b) each highlight is prefixed with a "block reference" with a hash that uniquely identifies a highlight

The combination of these two things is what allows the plugin to resync a file that has already been synced before, and insert new highlights at the right place in the document.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.0.0

**Comment by ThinkSpid** [comment]
That was a great update! I will have a try right now.

**Comment by ThinkSpid** [comment]
Wow, this is what I want! Now this plugin has done the perfect job for kindle highlight syncing. Especially for a large book, in which you have to write many thoughts after reading every chapter. Thank you for this useful plugin!
