### ISSUE TITLE
Request: expose ASIN

### ISSUE THREAD

**Issue by apollooakwood** [hadynz/obsidian-kindle-plugin#4]
Currently {{url}} is available in the plugin. The last part of the URL is the Amazon ASIN, which is useful for a couple reasons - I can use it to call up a cover image for the book, for example. (In sample link ``https://www.amazon.com/dp/B08S35PYWM`` the ASIN is ``B08S35PYWM``.) Could you expose this as {{asin}} perhaps?

This would also make possible a link to jump to the highlight in a kindle app, like this: ``[link](kindle://book?action=open&asin={{asin}}&location={{highlight.location}})`` - or the ``kindle://book?action=open&asin={{asin}}&location={{highlight.location}}`` could be {{applink}} or something? (I'm happy to put that string in my template though, everything but the {{asin}} part works as expected. ^_^

If there's an easy way to do this in the nunjucks template and I just haven't figured it out, I'd welcome the knowledge. Super, super great plugin, already a vast improvement over my previous workflow.

**Comment by hadynz** [comment]
This enhancement has been bundled as part of release [0.0.7](https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.0.7).

If you go to the plugin settings tab, you should see many new variables that I've added including your suggestions - `asin`, and `appLink`. If you change your template, you will need to reset and re-sync your highlights to use the latest templates again.
