### ISSUE TITLE
[FR] Add CLI

### ISSUE THREAD

**Issue by NightMachinary** [hadynz/obsidian-kindle-plugin#40]
I like to use this as a CLI, without Obsidian. Something like:
`kindle-clippings file.txt -to /some/dir -template someTemplate`

**Comment by hadynz** [comment]
This is out of scope for this plugin that operates only within Obsidian.

With that said, I will consider splitting out the kindle scraping and parsing engine into a separate library that can be used as CLI or a separate app outside of Obsidian.
