### ISSUE TITLE
Preference: don't create file if book has no highlights

### ISSUE THREAD

**Issue by apollooakwood** [hadynz/obsidian-kindle-plugin#5]
I'm not sure why Amazon has the notebook stick around for a book when all the notes and highlights from it are deleted, but I think it's probably safe to skip making a file in Obsidian for the ones where {{highlights}} contains no items. (IDK, maybe someone would want a file anyway? Preference?)

**Comment by hadynz** [comment]
This fix has been bundled as part of release [0.0.7](https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.0.7).
