### ISSUE TITLE
Space before first letter in book title breaks sync

### ISSUE THREAD

**Issue by jlouw** [hadynz/obsidian-kindle-plugin#50]
Hi Hady

I have a book that seems to have a space before the first letter of the title. This seems to break the sync.
My vault is in OneDrive and OneDrive does not allow empty spaces as the first letter....maybe that is part of the problem?
OneDrive therefore offers to rename the file and then adds an underscore at the start of the title....

![image](https://user-images.githubusercontent.com/1770987/120453031-f64fd280-c392-11eb-8d40-a742dcd2dc3a.png)

**Comment by jlouw** [comment]
It appears like this in Your Notes and Highlights

Your Kindle Notes For:
" The Warm-Hearted Snowman ": Christmas story: about small acts of kindness (Children's bedtime story picture book Book 1)

![image](https://user-images.githubusercontent.com/1770987/120454437-2d72b380-c394-11eb-8fb6-bcd674ebe2d9.png)

**Comment by hadynz** [comment]
Thanks for raising this issue and bringing it to my attention. I believe I have fixed it as part of the latest v0.2.14. Can you try it out and let me know if it resolves this issue for you?

**Comment by jlouw** [comment]
Hi Hady

It seems that this item wants to resync every time.

[image: image.png]

I am not sure if the RENAMING problem is related to the RESYNC problem....
I also have two other books out of about 150 that always try to resync....

Let me know what I can do to help you figure it out..

Best regards,.
Jean

**Comment by hadynz** [comment]
It might be easiest to isolate the problem for now to just the spacing issue.

If you don't mind, are you able to either:

(a) Choose a new directory for syncing (through settings), and do a sync from scratch
(b) Delete all the files that you've synced, and sync again from scratch

After using either of the above methods, confirm if there are no leading or trailing spaces in any of your file names.
