### ISSUE TITLE
Option to hide from the status bar

### ISSUE THREAD

**Issue by marcelinollano** [hadynz/obsidian-kindle-plugin#53]
I love love this plugin but I just use it from time to time when I finish reading books. To have it show all the time in the status bar seems a bit overkill. It would be nice to have an option to hide it from the status bar. Again, nothing super critical, but a nice addition nonetheless. Thank you!

**Comment by hadynz** [comment]
I'm closing this issue since the status bar has long been dropped. I had a plan to bring it back again but it has never been requested by a user so dropping this feature until it is requested again.
