### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by korm** [hadynz/obsidian-kindle-plugin#59]
Obsidian 0.12.5 on macOS 11.4

Kindle Highlights plugin has been installed for awhile.  Today I checked for updates (from within the Community Plugins section of Obsidian Settings).    An update for Kindle Highlights was available according to Obsidian.   Clicked to install.  "Failed to Install..." message.  I deleted the plugin and restarted Obsidian.  Now, from the Community Plugins list, I cannot install the plugin.

I created a new vault with nothing in it, turned off safe mode, and attempted to install Kindle Highlights plugin.  Failed.

Attached shows the installed plugins. 
<img width="185" alt="Screen Shot 2021-06-11 at 2 21 00 PM" src="https://user-images.githubusercontent.com/2934341/121732459-4b40c680-cac0-11eb-9b41-7fea96a9c871.png">

**Comment by hadynz** [comment]
I've just released a new version 0.2.16. Can you try getting latest and see if this version works for you please?

**Comment by korm** [comment]
Thank you.  I am able to succeed and install it.  I'll have to monitor it to determine if it is actually syncing again.
