### ISSUE TITLE
Fail on sync

### ISSUE THREAD

**Issue by jacobsenmd** [hadynz/obsidian-kindle-plugin#62]
I'm excited about this plugin! Great work. Unfortunately, it silently fails when I try using it with "My Clippings.txt":

<img width="559" alt="Screen Shot 2021-06-18 at 8 39 20 AM" src="https://user-images.githubusercontent.com/8184459/122570053-feee0d00-d010-11eb-9bc4-b5c29fd321a5.png">

**Comment by hadynz** [comment]
Do you mind if you send me your My Clippings file to my email? It will help me debug and fix the entry that is causing parsing to fail hadyos@gmail.com

**Comment by hadynz** [comment]
Thanks for sending me your file @jacobsenmd. I was able to recreate the issue and resolve it. 

Please check out the latest version that I just published ([0.2.17][1]) and let me know how you go!

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.2.17
