### ISSUE TITLE
highlight.page doesn't work correctly?

### ISSUE THREAD

**Issue by FrocketGaming** [hadynz/obsidian-kindle-plugin#69]
Love the plugin but I cannot get highlight.page or highlight.location to actually pull the correct page the highlight was on. 

For example; I have a book where the first highlight is on page 15 and that's what it also says in the notes on the Kindle app but the sync for {{highlight.page}} has it on 159 and each note only gets worse from there. The last highlight is on page 2500 even though the book only has 400 pages.

Some books are accurate but others aren't even close.

**Comment by hadynz** [comment]
Thanks for raising this @FrocketGaming. Something potentially could be off. So let's try an unpack the problem.

Firstly, what type of sync are you using? Are you uploading your My Clippings file or are you syncing from the Amazon cloud?

Are you able to take a screenshot of a given highlight in your Clippings file or the Amazon cloud, and another screenshot of what the plugin actually produces? That would demonstrate what the highlight `{page}` or `{location}` should be and give me a hint to what could've gone wrong.

**Comment by FrocketGaming** [comment]
> Thanks for raising this @FrocketGaming. Something potentially could be off. So let's try an unpack the problem.
> 
> Firstly, what type of sync are you using? Are you uploading your My Clippings file or are you syncing from the Amazon cloud?
> 
> Are you able to take a screenshot of a given highlight in your Clippings file or the Amazon cloud, and another screenshot of what the plugin actually produces? That would demonstrate what the highlight `{page}` or `{location}` should be and give me a hint to what could've gone wrong.

Using the Amazon Cloud and I've tried both {page} and {location}, both gave the same results. Looking a bit further, the issue might not be with your plugin at all. I reviewed the books in question on the kindle app and the note locations are right but when I review it on the desktop read.amazon.com/notebook site, the kindle pages are wrong.  I'll have to see if I can find a way to re-sync my notes to the Amazon server.

**Comment by hadynz** [comment]
I was going to follow up and say that this is potentially the case. The dissonance between the page/location on the Kindle app, and how your highlights come through the Amazon notebook site. The latter acts as the source of truth for the plugin.
