### ISSUE TITLE
plugin is not syncing highlights from all books

### ISSUE THREAD

**Issue by sinayanaik** [hadynz/obsidian-kindle-plugin#74]

**Comment by hadynz** [comment]
Hi @sinayanaik. Can you provide some more information about the issue that you are experiencing and how it can possibly be replicated?

**Comment by sinayanaik** [comment]
I have annotated nearly 50 books but the plugin is only syncing 10-20 books

**Comment by hadynz** [comment]
Some more questions to try and help me understand the issue at play if I may:

1. Are you syncing via Kindle online or uploading your My Clippings file?
2. What version of the app are you running?
2. If you are syncing via Kindle online, can you see all your books when you goto https://read.amazon.com?

**Comment by sashankaryal** [comment]
If it's a "personal" doc or book, meaning you didn't get it from the Kindle store, there isn't an easy way to get your highlights to Obsidian. What I do is rather circuitous:
1. Go to the list of highlights on my iPad (or your device where the doc is).
2. Click on the little share icon.
3. Send it to email. (Make sure to have apple mail app installed and configured)
4. Use a nifty script to check my mail, extract the highlights html and sync it to obsidian.

Pain...

**Comment by hadynz** [comment]
If you want to get highlights for books that you haven't purchased from Amazon (and hence won't be available via the [Amazon notebook online][1], then the plugin allows you to upload your My Clippings file from device.

In terms of the bug that you have raised, I still don't understand how to recreate the problem.

Are you suggesting that this is an issue for books that you have purchased from Amazon and you are trying to import through the plugin?

If you can share with me some screenshots of your steps, and what you expect, that will probably help me understand the issue at play.

[1]: https://read.amazon.com/notebook

**Comment by hadynz** [comment]
Can you please try [v1.0.x][1] and let me know if its fixes the issue that you were running into?

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.0.0
