### ISSUE TITLE
Amazon India Store

### ISSUE THREAD

**Issue by deepu** [hadynz/obsidian-kindle-plugin#75]
I added this plugin on Obsidian. 
In the settings it's only showing I can only connect to Amazon US, Japan and Spanish kindle accounts. 

Is there a possibility to add to Amazon India Kindle account ?

**Comment by corlin** [comment]
i also has the problem ,i am from china main land ，is there a feature to switch the amazon zone；exp： china mainland，india，tw etc.

**Comment by hadynz** [comment]
> i also has the problem ,i am from china main land ，is there a feature to switch the amazon zone；exp： china mainland，india，tw etc.

@corlin Amazon does not have an online Kindle reading portal for china (e.g. https://read.amazon.cn). So there is no way for the plugin to be able to screen scrape your highlights

**Comment by hadynz** [comment]
@deepu I've added support for India in the latest version of the plugin https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/0.2.19

Try it out and let me know if it is working for you
