### ISSUE TITLE
pages, publication, and publisher not populating

### ISSUE THREAD

**Issue by writtenfool** [hadynz/obsidian-kindle-plugin#76]
I can't pull any of these fields from Amazon using the template provided oob. It places empty lines. Love this plugin, cheers for bringing it to us!

{% if pages %}* Pages: {{pages}}{% endif %}
{% if publication %}* Publication: {{publication}}{% endif %}
{% if publisher %}* Publisher: {{publisher}}{% endif %}

**Comment by hadynz** [comment]
Hey @writtenfool. Can you share with me an example of a book that you synced using the plugin which didn't bring the above pieces of information when you expected it to do so?

**Comment by writtenfool** [comment]
Connectome by Sebastian Seun.  I can't see where any kindle books have brought in this data.

**Comment by hadynz** [comment]
This should be fixed in [1.4.1][1]. Can you try it out and confirm?

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.1
