### ISSUE TITLE
The Field {{color}} does not work

### ISSUE THREAD

**Issue by rothdata** [hadynz/obsidian-kindle-plugin#77]
The Field {{color}} does not work. 

By the way, this is my workaround for the German Amazon-site:
{% if asin %}[Link zu Amazon](https://www.amazon.de/dp/{{asin}}){% endif %}  ツ

Thank you for the great plug-in.

**Comment by hadynz** [comment]
I believe this issue took place because you were using a non-English version of Amazon.

This should be fixed in [1.4.0][1]. Please give it a try and let me know if it has resolved this issue for you.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.0
