### ISSUE TITLE
Dropping the "the" from the display of note titles 

### ISSUE THREAD

**Issue by seatrout** [hadynz/obsidian-kindle-plugin#82]
I have 165 Kindle titles with highlights extracted by this plugin. Thank you. 

However, 53 of them start with the word "The" and I would really prefer it if they were listed in the file manager in an order that ignored this. It's not so much the file names themselves that should be altered: just the other in which they are displayed, if that's possible, so that eg "The Complete works of Joseph Conrad" was displayed immediately before "Complete works of William Shakespeare".

**Comment by hadynz** [comment]
That's a fantastic and really useful feature that I think would benefit many others users.

I am currently knee deep in updating the plugin to be able to sync a book multiple times over. I'll pick this up afterwards.

Can you think of any other words besides "The" at the start of the sentence that the plugin can optionally strip out for convenient listing of files?

**Comment by hadynz** [comment]
Checkout my comment in [this thread][1]. It should be applicable for you too.

I will still leave this issue open until I introduce the feature you are asking for.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/issues/78#issuecomment-955645229

**Comment by hadynz** [comment]
Version [1.3.0][1] has introduced the ability for you to specify the template to use for your file name for a given book. You can easily use Nunjucks templating now to strip out any trailing "the" and achieve what you wanted.

Have a go and let me know if it is working for you.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.3.0
