### ISSUE TITLE
Not all my books are synced.

### ISSUE THREAD

**Issue by ananggadipa** [hadynz/obsidian-kindle-plugin#90]
I use upload My Clippings.txt but not all books highlights are synced. I use v1.0.3.
It says imported 62 books, which is not all the book highlights found on My Clippings.txt.
Is there any limit of the books? I try reset but still the same.

I try adding a new folder and it could add the remaining book (it says 73 books, the previous highlight is still left on the first folder).

I can replicate this issue.

When first parsing this warning appear on the top right:
Error parsing  My Clippings.txt
File already exists.

**Comment by hadynz** [comment]
It looks like what is happening is that the Plugin is running into a conflict with two different books that end up having the same "short name" and hence you are getting the "File already exists" error, and no more books are being processed.

Can you confirm what operating system and version of Obsidian you are using.

Can you also send me your Clippings file. Either upload and share link or send it to hadyos at gmail.com.

**Comment by ananggadipa** [comment]
Ah, that's true! There's two book having the same short name.
Thanks for your help!
