### ISSUE TITLE
Feature Request: one file per highlight/note

### ISSUE THREAD

**Issue by evantravers** [hadynz/obsidian-kindle-plugin#91]
First off… I **love** this plugin… thank you so much.

Have you considered importing each highlight / note as a separate file named based on it's position in the document?

I _love_ linking to or block referencing quotes from my highlights in my notes but each time I re-import it wipes out the block references. If they were in stably named files, the references would be "safe."

**Comment by hadynz** [comment]
Can you walk me through an example of how this could look like to get a better understanding?

Also are you using the latest 1.0.x version of the plugin? This major version changed the contract of the highlights. Each highlight will have a special block quote reference before an annotation which is used by the plugin to resync new annotations in the right place. 

You should be able to use the reference or add your own custom reference after it.

**Comment by evantravers** [comment]
I hadn't run a sync in a long while because of this… let me check your smart new feature and get back with you.

**Comment by evantravers** [comment]
Playing around with the new sync… it seems like a great solution to my problem, thank you! My thought was to have a folder for the book, and a single file per highlight… that way you wouldn't have to be as clever inserting new highlights, and it'd be easier to track in git.

**Comment by evantravers** [comment]
I think the `^ref-<id>` model works ok… but it fails if you use a highlight template like:

```markdown
> {{text}}

loc: [{{location}}]({{appLink}})

{% if note %}{{note}}{% endif %}
```
It looks like the `^ref-id` is magically added at the very beginning of the template, and therefore if you want to add quotes or the `>` character, it doesn't quite link. The reference doesn't carry over to the whole block and note. `# header` references carry over till the next header… (which is why I use them for scripture references)

If we did the "file per highlight" pattern I described, then you could reference the whole file.

**Comment by evantravers** [comment]
I can't even seem to reference by block using the default template… when I type in [^ref-2346] on a string that includes [^ref-2346], it creates a new reference at the end!

Could we try making a template tag for the unique ID, and let me put it at the end of the quote? That seems to work with Obsidian's block references. Something like:

```markdown
> {{text}}{{id}}

loc: [{{location}}]({{appLink}})

{% if note %}{{note}}{% endif %}
```

Which might generate:

```markdown
> Things will seem better after you’ve eaten and slept.” “Really?” she asked. Bitter and challenging. “Well, not necessarily,” I admitted. “But it’s easier to deal with things when you’ve had some rest and some breakfast.” ^ref-16522 

loc: [692](kindle://book?action=open&asin=B00I8289A0&location=692)

I _love_ this quote.
```

**Comment by hadynz** [comment]
You've raised exactly the same point that has also been raised in https://github.com/hadynz/obsidian-kindle-plugin/issues/93.

I will look to move the auto-generated block references to the end of the annotation block

**Comment by evantravers** [comment]
👍👍

Let me know if you need someone to dev test or whatever. Happy to help.

**Comment by hadynz** [comment]
Are you OK if we close this issue (a highlight per file) to try and achieve the outcome that you want by fixing block references (i.e. #93)?

**Comment by evantravers** [comment]
Yeah, that's fine.
