### ISSUE TITLE
Can't sign out of Amazon account

### ISSUE THREAD

**Issue by poeticua** [hadynz/obsidian-kindle-plugin#92]
I moved some of my files around after syncing, which seems to have produced some weirdness. 

When I try to sign out of my Amazon account, I'm presented with the following:

![Obsidian_0TS2GSKjdG](https://user-images.githubusercontent.com/87426659/140331407-7fe9e705-2e06-400a-9ac4-d22d412a6fe8.png)

As you can see, it also notes I've never synced. But I'm also told I last synced a few seconds ago:

![Obsidian_pOABrYy2hT](https://user-images.githubusercontent.com/87426659/140331235-462d7aa3-3b13-43cc-a918-341a2b26de0a.png)

The plugin itself just says "Signing out..." indefinitely as if stuck on something. If I change to another plugin and return to it, it once again presents me with the "Sign out" option as if the previous attempt had never occurred.

Similarly, if I try to initiate sync, it's stuck on "Logging into amazon.com" indefinitely. 

I clearly bungled something up, is there a way to fully reset the plugin settings? Even if I disable and/or uninstall, it automatically hooks into what it thinks is my authenticated Amazon account.

**Comment by PCB64** [comment]
I’m having the same problem after the plug-in update, and I have not mess with anything. This must be a problem with the most recent update.

**Comment by hadynz** [comment]
Amazon's logout (from https://read.amazon.com/notebook) is currently broken and returns the same message that you posted in your screenshot.

I'll make a fix now to use Amazon.com's logout.

With that said... because logout is essentially not working, you shouldn't be seeing "Logging into amazon.com" indefinitely. Can you toggle Developer Tools in Obsidian and tell me if you see any errors in the console?

**Comment by hadynz** [comment]
I believe I have fixed this issue in the latest release. Can you download [v1.0.5][1] and confirm if that has also worked at your end?

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.0.5

**Comment by PCB64** [comment]
I will and let you know thanks


Perla Copernik
P. 1.305.218.1066
E. ***@***.***
W. http://www.PerlaCopernikPhotography | http://www.PrimeImageStudios.com

**Comment by PCB64** [comment]
It seems to be working now. At list syncing. But it did not work right away. It did allow me to log out so I could log back in when i clicked sync



This is the developer console. Im not sure what im looking at, but hopefully you’ll now. Thanks again!

Perla Copernik
P. 1.305.218.1066
E. ***@***.***
W. http://www.PerlaCopernikPhotography | http://www.PrimeImageStudios.com

**Comment by hadynz** [comment]
Your comment didn't have any console output. 

You happy that this issue has been resolved and I can close?

**Comment by PCB64** [comment]
Hi Hady, I have not done another sync but the one I did over the weekend (after you fix it) worked fine.
I did send you the screenshot though, it showed that everything seemed fine, at least with your plug-in, did you receive it?
Thank you very much for your help!

I have one last question though, is there a way to select only what I want to sync? Every time I delete the highlights from books I’m not interested in, the book comes back on my next sync…it’s not a big issue, but I wanted to ask nevertheless. Thanks again!
Regards

Perla

Perla Copernik
P. 1.305.218.1066
E. ***@***.***
W: http://www.perlacopernikphotography.com | http://www.Primeimage studios.com

**Comment by hadynz** [comment]
> I have one last question though, is there a way to select only what I want to sync? Every time I delete the highlights from books I’m not interested in, the book comes back on my next sync…it’s not a big issue, but I wanted to ask nevertheless. Thanks again!

You can think of the plugin as a simple transformer of your data. It uses either your Amazon cloud account or your My Clippings file as your source of truth. It makes no decision on what should not be synced.

So if you want a particular annotation that you've made for a book to be removed, currently you'd need to remove that annotation from your Kindle.

There is an open issue for allowing users to mark some books not to be synced https://github.com/hadynz/obsidian-kindle-plugin/issues/72.

**Comment by PCB64** [comment]
Thanks Hady, i tested the plugin again and it worked fine. Thanks for all your help


Perla Copernik
P. 1.305.218.1066
E. ***@***.***
W. http://www.PerlaCopernikPhotography | http://www.PrimeImageStudios.com

**Comment by chuckvtt** [comment]
I am trying to use version v1.1.0 but having difficulty logging out of Amazon and it seems that when I try to sync, the Amazon pop-up box does not appear, I think it is attempting to sync and not log in since it gives an error message when I try to log out.

I have been using the app without problems for quite a few months and the errors seemed to have started when the update a week ago.

I have also disabled/deleted the app and re-installed it a few times.

Can anyone offer any other suggestions for me to log into my Amazon account so that I can sync it up again? TYIA

**Comment by hadynz** [comment]
@chuckvtt I would prefer that you raise a new issue for the problem you are running into it to keep the threads separate.

My main tip for you to give me more information to help you:
* Toggle Obsidian's Developer Tools and see if there are any errors being displayed in the console
